<?php /*foreach ($this->getTotals() as $_code => $_total): ?>
	<?php if ($_total->getBlockName()): ?>
		<?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
	<?php else:?>
		<tr>
			<td style="border-top:1px solid #d6d6d6;border-right:1px solid #d6d6d6; text-align:center; width:75.4%; padding: 5px 0" colspan="3">
				<div style="padding:2px 15px; line-height:18px; text-align:right;"><?php echo $_total->getLabel()?></div>
			</td>
			<td style="border-top:1px solid #d6d6d6; text-align:center; width:24.3%;padding: 5px 0" >
				<div style="padding:2px 0; line-height:18px; text-align: left; text-indent: 8%; margin-right: 10px;"><?php echo $this->formatValue($_total) ?></div>
			</td>
		</tr>
	<?php endif?>
<?php endforeach*/?>



<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>

    
    <?php //echo "<pre>";print_r($_total->getData());echo "</pre>"; ?>
    <?php $totalData = $_total->getData(); ?>

    <?php if ($totalData['code'] == 'subtotal'){
        $TitleSubTotal = 'Sub - Total';
        $ValueSubTotal = $totalData['value'];
      }
    ?>

    <?php if ($totalData['code'] == 'discount'){
        $TitleDiscount = '(-) Discount';
        $ValueDiscount = $totalData['value'];
        $ValueDiscount = str_replace("-","",$ValueDiscount);
      }
    ?>

    <?php if ($totalData['code'] == 'shipping'){
        $TitleShipping = '(+) Shipping';
        $ValueShipping = $totalData['value'];
      }
    ?>

    <?php if ($totalData['code'] == 'grand_total'){
        $TitleGrandTotal = 'GRAND TOTAL';
        $ValueGrandTotal = $totalData['value'];
      }
    ?>

    <?php endif?>
<?php endforeach?>

<?php

// Total aftter discount
$TotalAfterDiscount = $ValueSubTotal - $ValueDiscount;
$FormatTotalAfterDiscount = number_format($TotalAfterDiscount,2);

?>


 <div class="final_total_main" style="display: table;width: 100%;border-top: 1px solid #ccc;">
        <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;"><?php echo $TitleSubTotal; ?></span></div>
        <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo number_format($ValueSubTotal,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;">(-) Discount<?php //echo $TitleDiscount; ?></span></div>
        <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo number_format($ValueDiscount,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;">Total</span></div>
        <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo $FormatTotalAfterDiscount; ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;"><?php echo $TitleShipping; ?></span></div>
        <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo number_format($ValueShipping,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;<?php if($_total->getLabel() == 'Grand Total'): ?>border-top: 1px solid #d6d6d6;<?php endif?>">
        <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;<?php if($_total->getLabel() == 'Grand Total'): ?>font-weight: bold;<?php endif?>"><?php echo $TitleGrandTotal; ?></span></div>
        <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo number_format($ValueGrandTotal,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>
