<meta property="og:site_name" content="HappilyUnmarried" />
<meta property="og:title" content="Shout out to the Naughty Ones from Happily Unmarried." />
<meta property="og:description" content="This Christmas, tell us how naughty you have been. 3 most interesting entries would win Happily Unmarried goodies." />
<meta property="og:type" content="article" />
<meta property="og:image" content="<?php echo Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group5/image');?>" />
<link rel="image_src" href="<?php echo Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group5/image');?>" />
