<div class="congrats_page">
	<h1>CONGRATULATIONS!</h1>

	<p>You're officially naughty and we love you owned up to it.</p>
	<p>Remember, naughty and proud!</p>

	<div class="socila_media_div">
		<div class="heading">Spread the Love and Share the Awesomeness!</div>
		<div class="sovial_icon_div">
			<a href="#"><img src="<?php echo $this->getSkinUrl('images/fb-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this->getSkinUrl('images/tw-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this -> getSkinUrl('images/google-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this -> getSkinUrl('images/pin-icon.png');?>"></a>
		</div>
	</div>
</div>


<div class="main_container_new xmaspage">
	<div class="banner_new">
		<img src="<?php echo $this->getSkinUrl()?>images/banner_new.jpg" />
	</div>

	<div class="news_div">
		<h2>Let the Old Fat Man deal with all the goody two shoes.</h2>
		<p>Tell us how naughty you've been this year. The naughtiest three win Happily Unmarried goodies.</p>
<p>Mark your calendars (like Teja), because the winners shall be declared on the <span class="date">22nd of December!</span></p>
	<h3>Oh, and HO HO HO!</h3>
	</div>

	<div class="form_div">	
		<p>Dearest Happily Unmarried,</p>
		<div class="form_content">
		<!-- <p>Your sinful letter.</p>

		<p>For eg. - </p> -->
			<!-- <p class="example">	“I have been at my naughtiest when I put up a fake wedding card on a co-worker’s Facebook profile. The number of likes he got were the most he ever got. His mom actually called to ask him about it.”</p> -->
		<!-- <p>(In 50 words maximum, please. We don’t have much of an attention span when drunk! )</p> -->
		<textarea class="form_textarea">
“I have been at my naughtiest when I put up a fake wedding card on a co-worker’s Facebook profile. The number of likes he got were the most he ever got. His mom actually called to ask him about it.”
(In 50 words maximum, please. We don’t have much of an attention span when drunk! )
		</textarea>

		</div>

		<p>Naughty forever,</p>

		<form>
			<div class="input_field"><input type="text"></div>
			<div class="input_field"><input type="text"></div>
			<h3>Merry XXXMas!</h3>

			<button>SUBMIT</button>
		</form>
	</div>

</div>

