<script type="text/javascript">

start_slideshow(1, 3, 3000);

function start_slideshow(start_frame, end_frame, delay) {
	id = setTimeout(switch_slides(start_frame,start_frame,end_frame, delay), delay);
}

function switch_slides(frame, start_frame, end_frame, delay) {
	return (function() {
		Effect.Fade('slide' + frame, { duration: 1.0 });
		if (frame == end_frame) { frame = start_frame; } else { frame = frame + 1; }
		Effect.Appear('slide' + frame, { duration: 1.0 });
		if (delay == 1000) { delay = 3000; }
		id = setTimeout(switch_slides(frame, start_frame, end_frame, delay), delay);
	})
}

function stop_slideshow() {
	clearTimeout(id);
}

</script>

<div id="introhomepage" style="height: 230px; position: relative;" onmouseover="stop_slideshow()" onmouseout="start_slideshow(1, 3, 8000)">
	<div id="slide1" style="position: absolute; top: 0pt; left: 0pt; display: block; z-index: 3; opacity: 1;">
		<a href='http://www.yourdomain.com/path/to/webpage.html'>
			<img border='0' src='<?php echo $this->getUrl() . 'media/harpreet/slider/default/banner1.jpg' ?>' />
		</a>
	</div>
	<div id="slide2" style="position: absolute; top: 0pt; left: 0pt; display: none; z-index: 2; opacity: 0;">
		<a href='http://www.yourdomain.com/path/to/webpage.html'>
			<img border='0' src='<?php echo $this->getUrl() . 'media/harpreet/slider/default/banner2.jpg' ?>' />
		</a>
	</div>
	<div id="slide3" style="position: absolute; top: 0pt; left: 0pt; display: none; z-index: 1; opacity: 0;">
		<a href='http://www.yourdomain.com/path/to/webpage.html'>
			<img border='0' src='<?php echo $this->getUrl() . 'media/harpreet/slider/default/Black_Board.jpg' ?>' />
		</a>
	</div>
</div>