<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>

	<div id="onepagecheckout_loginbox" class='op_login_area'>

		<!-- <div class='close_la' onclick='close_login();'></div> -->
	    <!--div class="page-title">
	        <span><?php // echo $this->__('Login to your Account') ?></span>
	    </div-->

		<?php
		$login_url	= $this->getUrl('*/*/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
		$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
		if($http_mode)
			$login_url	= str_replace('http:', 'https:', $login_url);
		?>
	    <form method="post" id="login-form" action="<?php echo $login_url ?>" autocomplete="on">
	        <div class="boxcontent">
				<div class='full'>
					<label>
						<?php echo $this->__('Email ID') ?>
						<sup>*</sup>
					</label>
					<div class="data_area">
						<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="t1 input-text required-entry validate-email" />
					</div>
				</div>
				<div class='full'>
					<label>
						<?php echo $this->__('Password') ?>
						<sup>*</sup>
					</label>
					<div class="data_area">
						<input type="password" name="login[password]" class="t1 input-text required-entry validate-password" id="pass" />
					</div>
				</div>
	        </div>
	        <div class="buttons-set">
	            <button type="submit" class="button happy_button" name="send" id="send2"><?php echo $this->__('sign in') ?></button>
	            <span class="please-wait" id="login-please-wait" style="display:none;">
	                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
	            </span>

	            <a href="javascript:void(0);" class="onepagecheckout_forgotlink" onclick='open_forgot();'><?php echo $this->__('Forgot Your Password? Lol.') ?></a>
	        </div>
	    </form>
	    <script type="text/javascript">
	    //<![CDATA[
	        var loginForm = new VarienForm('login-form', true);
	    //]]>
	    </script>
	</div>
<?php endif; ?>
