<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">

    <h2 id="checkout-review-table-heading">
        <?php echo $this->__('Your Order Summary') ?>
        <button class="continue button happy_button" id="review-step-continue">Proceed To Payment</button>
    </h2>

    <table class="order-products-table" id="checkout-review-table">
        <col />
        <col width="1" />
        <col width="1" />
        <?php
        $colspan	= 1;
        if ($this->helper('tax')->displayCartBothPrices()):
        	$colspan	= 2;
        ?>
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th class="a-right opc_review_total_column"><?php echo $this->__('Price') ?></th>
                <th class="a-right opc_review_qty_column"><?php echo $this->__('Quantity') ?></th>
                <th class="a-right opc_review_total_column"><?php echo $this->__('Total') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>

    <?php echo $this->getChildHtml('totals'); ?>

    <div id="checkout-coupon-discount-load">
        <?php echo $this->getChildHtml('coupon') ?>
    </div>

    <div class="review-step-bottom-bar">
        <div class="shipping_info_box">
            <h4>Shipping Information</h4>
            <div class="shipping_info" id="checkout-shipping_info-load"></div>
        </div>
        <div class="delivery_date_box">
            <h4>Delivery Date</h4>
            <div class="delivery_date">
                <p>3 - 4 working days</p>
            </div>
        </div>
        <div class="proceed_to_payment_box">
            <button class="continue button happy_button" id="review-step-continue">Proceed To Payment</button>
        </div>
    </div>

</div>

<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
