<div class="category_toggle_area">
    <div id="category_toggle_btn" >
        <img src="<?php echo $this->getSkinUrl('images/mobile/category_ico.png');?>"  alt="Category Toggle Btn" class="cat_toggle"/>
    </div>
    <div class="main_category_area">
        <div class="tip_arrow"></div>
        <div class="main_category_space">
           <div class="shop_by_category">SHOP BY CATEGORIES</div>
           <div class="main_category_links" id="main_category_links">
                <div class="category_loading"></div>
           </div>
            <div class="find_my_gift_title">
                <span>Find My Gift</span>
                <a class="gift_show_btn">Yes! Show me PLEASE!</a>
            </div>
            <div class="close_left_nav_area">
                <div class="close_left_nav_btn">
                    <span class="close_text">Close</span>
                </div>

            </div>
        </div>
    </div>

    <div class="toggle_overlay"></div>

</div>
