<div class="home_category_wrapper" id="home_category_wrapper">
	<div class="shop_by_category">SHOP BY CATEGORIES</div>
</div>

<div class="footer_find_gift_area">
	<div class="footer_find_gift_wrapper"><img src="<?php echo $this->getSkinUrl('images/mobile/footer_gift_ico.png'); ?>" alt=" " />
		<span class="find_gift_text">Find My Gift</span>
		<a class="gift_show_btn">YES! Show me PLEASE!</a>
	</div>
</div>
