<?php
$elasticSearch = $this->getModel();
$searchText = $this->getSearchText();
$resultSet = $this->getResult();
$searchResponseType = $this->getSearchResponseType();
$searchResponseSuggestion = $this->getSearchResponseSuggestion();
?>

<?php if($searchResponseType == $elasticSearch::RESULT_TYPE_SUGGESTION): ?>

	<ul class="autosuggest-results">
		<li id="search-closest-match">
			<a href="<?php echo $this->helper('elastic')->getCorrectedUrl($searchResponseSuggestion); ?>" class="table search_no_products">
				<div class="table-cell pl-10">
					<span>
						Did you mean <b class="correction"><?php echo $searchResponseSuggestion; ?></b>?
					</span>
				</div>
			</a>
		</li>
	</ul>

<?php elseif($searchResponseType == $elasticSearch::RESULT_TYPE_FAILED): ?>

	<ul class="autosuggest-results">
		<li id="search-no-match">
			<a href="#" class="table search_no_products">
				<div class="table-cell pl-10">
					<span>
						No results found for <b><?php echo $searchText; ?></b>
					</span>
				</div>
			</a>
		</li>
	</ul>

<?php else: ?>

	<ul class="autosuggest-results">
		<?php if(count($resultSet) > 0): ?>
			<?php foreach($resultSet as $product): ?>
				<li>
					<a href="<?php echo $product['url']; ?>" class="table">
						<div class="table-cell image-cell">
							<img src="<?php echo $this->getSkinUrl('images/homepage/lazyloader_placeholder.png'); ?>" data-original="<?php echo $product['image']; ?>"/>
						</div>
						<div class="table-cell pl-10">
							<span><?php echo preg_replace('/\b' . preg_quote($searchText, "/") . '/i', "<b>\$0</b>", $product['name']); ?></span> 
							<!--<span><?php //echo preg_replace('/\b' . preg_quote($searchText, "/") . '\b/i', "<b>\$0</b>", $product['name']); ?></span>-->
						</div>
					</a>
				</li>
			<?php endforeach; ?>
		<?php endif; ?>
	</ul>

	<script type="text/javascript">decorateGeneric($$('.autosuggest-results li'), ['', '', 'first', 'last'])</script>

	<script type="text/javascript">
	jQuery('.autosuggest-results img').lazyload();
	</script>

<?php endif; ?>
