<!-- 
<div class="page-head">
    <h3><?php //echo $this->__('Payment transaction has been canceled.') ?></h3>
</div>
<p><?php //echo $this->getErrorMessage() ?>.</p>
<p><?php //echo $this->__('Please <a href="%s">continue shopping</a>.', $this->getContinueShoppingUrl()) ?></p> -->

<!-- Start of payu failure page added by Sourav on 26th June 2014 to replace failure page for payu -->

<div class="transaction-cancelled">
	<img src="http://happilyunmarried.iksulabeta.com/skin/frontend/happy/default/images/HUW%20-%20Payment%20Transaction%20Cancelled-image.jpg" alt="" />
</div>
<div class=" transaction-cancelled-header">Payment transaction has been cancelled!</div>
<div class=" transaction-cancelled-text">
	Sometimes Life is hard you. But you should'nt be put down S*** happens! just keep calm and keep Shopping!
</div>
<a href="/"><div class=" transaction-bottom"><span class="happy_button keep_shopping_button">KEEP SHOPPING</span></div></a>

<!-- End of payu failure page added by Sourav on 26th June 2014 to replace failure page for payu -->