<?php
$baseUrl = Mage::helper('core/url')->getCurrentUrl();
$productUrl = str_replace($this->getUrl(), '', $baseUrl);
$urlParams = explode("/", $productUrl);
$paramCount = count($urlParams);
$defaultCategory = $this->helper('explore')->getDefaultCategory();
$searchString = $this->getRequest()->getParam('search');
$renderedCategoryHeading = false;
?>

<?php
$findAGift = false;
$allParams = $this->getRequest()->getParams();
if(array_key_exists('gender', $allParams) OR array_key_exists('occasion', $allParams) OR array_key_exists('personality', $allParams)) {
	$findAGift = true;
}
?>

<?php
$session = Mage::getSingleton('core/session');
$breadcrumbs = $session->getBreadcrumbData();
$session->unsBreadcrumbData();

$cat_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$categoryCurr = Mage::getModel('catalog/category')->load($cat_id);

?>

<div class="category_head product_category_head<?php if($paramCount > 3): ?> category_has_subcategories<?php endif; ?>">
	<?php $count = 0; foreach($breadcrumbs as $urlKey => $urlParam): ?>
		<?php if(strripos($urlKey, 'category') !== false AND $defaultCategory != str_replace("category", "", $urlKey)): $count++; ?>
			<?php $category = Mage::getModel('catalog/category')->load(str_replace("category", "", $urlKey)); ?>
			<?php if($count == 1): ?>
				<?php $parentCategoryId = $category->getId(); ?>
				<?php $renderedCategoryHeading = true; ?>
				<div class="category_label" id="category<?php echo $parentCategoryId; ?>">
					<a href="<?php echo $category->getUrl(); ?>">
						<?php if($category->getActiveThumbnail()): ?>
							<img class="category_thumbnail" src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $category->getActiveThumbnail(); ?>" />
						<?php endif; ?>
						<span><?php echo $categoryCurr->getName(); ?></span>
					</a>
				</div>
				<?php if($category->getData('subcategory_colors')): ?>
					<?php $colorCodes = explode(',', $category->getData('subcategory_colors')); ?>
					<style type="text/css">
					#category<?php echo $parentCategoryId; ?> .category_head .category_description { color: #<?php echo trim($colorCodes[0]); ?>; }

					<?php if(count($colorCodes) > 1): ?>
						#label_master_<?php echo $parentCategoryId; ?> .subcategory_label { background-color: #<?php echo trim($colorCodes[1]); ?>; }
						#label_master_<?php echo $parentCategoryId; ?> .subcategory_label:hover { background-color: #<?php echo trim($colorCodes[2]); ?>; }
						#label_master_<?php echo $parentCategoryId; ?> .active_label { background-color: #<?php echo trim($colorCodes[3]); ?>; }
						#label_master_<?php echo $parentCategoryId; ?> .active_label:hover { background-color: #<?php echo trim($colorCodes[3]); ?>; }
					<?php endif; ?>

					</style>
				<?php endif; ?>
			<?php else: ?>

			<?php

			  //   $_cat = new Mage_Catalog_Block_Navigation();
			  //   $curent_cat = $_cat->getCurrentCategory();
			  //   $category_ids = $_cat->getCurrentCategory()->getParentCategory()->getPath();  
			  //   $cat_id = explode('/',$category_ids);
			  //   $top_parent_model_id = $cat_id[4];
			    
			  //   	//if($cat_id[3] == 75){
			  //   	$_category = Mage::getModel('catalog/category')->load($cat_id[3]);
					// if($_category['featured_category_parent'] == 1){

			  //   	if($top_parent_model_id != $category->getId()){
			?> 
<!-- 				<div class="category-option">
					<span class="category-option-text">
						<span class="subcategory_label active_label" id="cat<?php //echo $category->getId(); ?>">
							<?php //echo $category->getName(); ?>
						</span>
					</span>
					<span class="category-option-sign"></span>
				</div> -->
			<?php 
				// 	} 
				// }
			?>

<!-- 
				<ul class="subacategory_labels" id="label_master_<?php //echo $parentCategoryId; ?>">
					<a href="<?php //echo $category->getUrl(); ?>" class="subcategory_label active_label" id="cat<?php //echo $category->getId(); ?>">
						<?php //echo $category->getName() ?>
					</a>
				</ul> -->

				 <?php $parentCategory = Mage::getModel('catalog/category')->load($category->getParentId()) ?>

					<?php 

						//if($cat_id[3] != 75){
				    	$_category = Mage::getModel('catalog/category')->load($cat_id[3]);
						if($_category['featured_category_parent'] != 1){

						?>
						<div class="category-option">
							<span class="category-option-text">
								<span class="subcategory_label active_label" id="cat<?php echo $category->getId(); ?>">
									<?php echo $category->getName(); ?>
								</span>
							</span>
							<span class="category-option-sign"></span>
						</div>
					<?php } ?>

				<div class="category_description"><?php echo $parentCategory->getData('home_tagline') ?></div>

	            <?php $subcategories = explode(',', $parentCategory->getChildren()); ?>
	            <?php if($parentCategory->getData('children_count') > 0): ?>
	            <div class="category-option-area">
	                <div class="tip_arrow"></div>
	                <div class="main-area">
	                    <ul>
	                        <?php foreach($subcategories as $subcategoryId): ?>
	                            <?php $subcategory = Mage::getModel('catalog/category')->load($subcategoryId); ?>
	                            <?php if($subcategory->getData('is_active')): ?>
	                                <li>
	                                    <a href="<?php echo $subcategory->getUrl() ?>" class="subcategory_label" id="<?php echo 'cat' . $subcategory->getData('entity_id'); ?>"><?php echo $subcategory->getName(); ?></a>
	                                </li>
	                            <?php endif; ?>
	                        <?php endforeach; ?>
	                    </ul>
	                </div>
	            </div> 
	            <div class="toggle_overlay" id="category_toggle" style="display: none;"></div>
	            <?php endif; ?>

			<?php endif; ?>
		<?php endif; ?>
	<?php endforeach; ?>

	<?php if($searchString && !$renderedCategoryHeading): ?>
		<div class="category_label" id="category0">
			<form method="GET" action="<?php echo $this->getUrl('catalogsearch/result') ?>" name="back_to_search" id="back_to_search">
				<input type="hidden" name="q" value="<?php echo $searchString; ?>" />
				<input type="hidden" name="order" value="relevance" />
			</form>
			<a href="#" onClick="$('back_to_search').submit(); return false;" class="m_search_string_on_product_page">
				<div class="arrow-left"></div>
				<span><?php echo $this->__('Back to search: '); ?></span>
				<span class="search_string"><?php echo $searchString; ?></span>
			</a>
		</div>
	<?php endif; ?>

	<?php if($findAGift): ?>
		<div class="category_label" id="category0">
			<form method="GET" action="<?php echo $this->getUrl('find_a_gift') ?>" name="back_to_search" id="back_to_search">
				<?php foreach($allParams as $param => $value): ?>
					<?php if($param != 'id'): ?>
						<input type="hidden" name="<?php echo $param; ?>" value="<?php echo $value; ?>" />
					<?php endif; ?>
				<?php endforeach; ?>
			</form>
			<a href="#" onClick="$('back_to_search').submit(); return false;" class="search_string_on_product_page">
				<div class="arrow"></div>
				<span><?php echo $this->__('Back to Gift Finder Results'); ?></span>
			</a>
		</div>
	<?php endif; ?>
</div>
<script type="text/javascript">decorateGeneric($$('.main-area ul li'), ['', '', '', 'last'])</script>
<style>
.category-option {
	display: none;
}
.product_category_head {
	margin-bottom: 5px;
}
</style>