<div class="cms_likeus">
	<div class="likeus_text">Like Us</div>
	<div class="likeus_image">
		<div class="like_facebook"><a href="#"><img src="<?php echo Mage::getDesign()->getSkinUrl().'images/general/hu_facebook.png'; ?>"/></a></div>
		<div class="like_twitter"><a href="#"><img src="<?php echo Mage::getDesign()->getSkinUrl().'images/general/hu_twitter.png'; ?>"/></a></div>
		<div class="like_gplus"><a href="#"><img src="<?php echo Mage::getDesign()->getSkinUrl().'images/general/hu_google.png'; ?>"/></a></div>
	</div>
</div>