<?php

/**
 * @var $this Mage_Sales_Block_Order_Totals
 * @see Mage_Sales_Block_Order_Totals
 */
?>
<?php /*foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <tr class="<?php echo $_code?>">
        <td <?php echo $this->getLabelProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $_total->getLabel()?></strong>
            <?php else:?>
            <?php echo $_total->getLabel()?>
            <?php endif?>
        </td>
        <td <?php echo $this->getValueProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->formatValue($_total) ?></strong>
            <?php else:?>
            <?php echo $this->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif?>
<?php endforeach */ ?>

<?php /*foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>

    <?php if($_total->getLabel() == 'Grand Total'): ?>
    <?php $Title = 'GRAND TOTAL'; ?>
    <?php endif ?>
    <?php if($_total->getLabel() == 'Subtotal'): ?>
    <?php $Title = 'Sub - Total'; ?>
    <?php endif ?>
    <?php if($_total->getLabel() == 'Shipping & Handling'): ?>
    <?php $Title = '(+) Shipping'; ?>
    <?php endif ?>
    <?php if($Title == ''): ?>
    <?php $Title = $_total->getLabel() ; ?>
    <?php endif ?>

        <div class="final_total_main" style="display: table;width: 100%;<?php if($_total->getLabel() == 'Grand Total'): ?>border-top: 1px solid #d6d6d6;<?php endif?>">
            <div style="display: table-cell;width: 43%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
                <span style="padding-right:8px; <?php if($_total->getLabel() == 'Grand Total'): ?>font-weight: bold;<?php endif?>"><?php echo $Title; ?></span></div>
            <div style="display: table-cell;width: 8%;border-right: 1px solid #ccc;font-size: 14px;">&nbsp;</div>
            <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;">&#x20B9; <?php echo str_replace("`","",$this->formatValue($_total)) ?></div>
            <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
        </div>

    <?php $Title = ''; ?>

    <?php endif?>
<?php endforeach*/?>





<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>

    
    <?php //echo "<pre>";print_r($_total->getData());echo "</pre>"; ?>
    <?php $totalData = $_total->getData(); ?>

    <?php if ($totalData['code'] == 'subtotal'){
        $TitleSubTotal = 'Order Amt';
        $ValueSubTotal = $totalData['value'];
      }
    ?>

    <?php if ($totalData['code'] == 'discount'){
        $TitleDiscount = '(-) Discount';
        $ValueDiscount = $totalData['value'];
        $ValueDiscount = str_replace("-","",$ValueDiscount);
      }
    ?>

    <?php if ($totalData['code'] == 'shipping'){
        $TitleShipping = '(+) Shipping';
        $ValueShipping = $totalData['value'];
      }
    ?>

    <?php if ($totalData['code'] == 'grand_total'){
        $TitleGrandTotal = 'GRAND TOTAL';
        $ValueGrandTotal = $totalData['value'];
      }
    ?>

    <?php endif?>
<?php endforeach?>

<?php

// Total aftter discount
$TotalAfterDiscount = $ValueSubTotal - $ValueDiscount;
$FormatTotalAfterDiscount = number_format($TotalAfterDiscount,2);

?>


 <div class="final_total_main" style="display: table;width: 100%;border-top: 1px solid #ccc;">
        <div style="display: table-cell;width: 51%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;"><?php echo $TitleSubTotal; ?></span></div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;padding-left:10px;">&#x20B9; <?php echo number_format($ValueSubTotal,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 51%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;">(-) Discount<?php //echo $TitleDiscount; ?></span></div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;padding-left:10px;">&#x20B9; <?php echo number_format($ValueDiscount,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 51%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;">Total</span></div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;padding-left:10px;">&#x20B9; <?php echo $FormatTotalAfterDiscount; ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;">
        <div style="display: table-cell;width: 51%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;"><?php echo $TitleShipping; ?></span></div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;padding-left:10px;">&#x20B9; <?php echo number_format($ValueShipping,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

 <div class="final_total_main" style="display: table;width: 100%;<?php if($_total->getLabel() == 'Grand Total'): ?>border-top: 1px solid #d6d6d6;<?php endif?>">
        <div style="display: table-cell;width: 51%;border-right: 1px solid #ccc;text-align: right;font-size: 14px;padding: 4px 0;">
            <span style="padding-right:8px;<?php if($_total->getLabel() == 'Grand Total'): ?>font-weight: bold;<?php endif?>"><?php echo $TitleGrandTotal; ?></span></div>
        <div style="display: table-cell;width: 23%;border-right: 1px solid #ccc;text-align: center;font-size: 14px;padding-left:10px;">&#x20B9; <?php echo number_format($ValueGrandTotal,2) ?></div>
        <div style="display: table-cell;width: 26%;text-align: center;font-size: 14px;"></div>
</div>

