<div class="accordion_format">

	<div class="fixed_spot">
		<h2>About Us</h2>
		<div class="matter">

			<img class="f-left w-30" src="<?php echo $this->getSkinUrl('images/about_us/HUWM---About-Us---Open_03.png') ?>" alt=""/>
			<h3>Who are We?</h1>

			<p>Happily Unmarried was anti established in 2003 with no vision and no business plan. Actually at somepoint we did make a business plan but according to that we should have retired 5 years ago.</p>
			<p>We make fun products, we do music festivals, we work with corporates when they want to do interesting work and lately we have been doing a lot of projects involving branding, communication, interiors, marketing all rolled into one (we are trying to think of a name for someone who does all that but no luck yet).<br><br></p>

			<h3>Keeping it simple!</h1>

			<p>This website was partially designed by people who hate to shop, so we have tried to keep things as simple as they possibly can be. We don't show videos when an illustration would do, we don't make the cursor do funny things while you wait for your order to get processed. Since you know how ridiculously well priced we already are we don't offer unrealistic discounts either.</p>

		</div>
	</div>

	<div class="accordion">

		<h2>Brief History</h2>
		<div class="matter">

			<img class="f-left w-40" src="<?php echo $this->getSkinUrl('images/about_us/HUWM---About-Us---Open_07.png') ?>" alt=""/>

			<p>The history of Happily Unmarried starts with the Neanderthals. Our team of archaeologists can say with a lot of surety that all the Neanderthals were happily unmarried. We even have a Tee shirt which says that. Of course since our programmers are still in the Neanderthal stage they may have forgotten to link it to the shopping page. So go to the shopping page, click on Tee shirts and voila!</p>

			<p>As time progressed, we became humans. Suddenly there was a general pressure to make life more complicated.The making life complicated thing continued for a few thousand years. Meanwhile in a civil war against making things complicated, we lost Dinosaurs, Dodos, most of the Tigers and a few other 100 thousand creatures which we can't  remember, but all of them were happily unmarried (now you get the picture).</p>

			<img class="f-right w-50" src="<?php echo $this->getSkinUrl('images/about_us/about-us-tshirt.png') ?>" alt=""/>

			<p>Then came the year 2003 and people said enough is enough. The Happily Unmarrieds re-grouped under the Happily Unmarried company and started propagating their wisdom to all.</p>

			<p>Things like:</p>

			<p> - Have fun with what you do</p>

			<p> - Keep life simple</p>

			<p> - Mind the gap</p>

			<p> - Do not wear ties to work</p>

			<p> - Press Star key to continue</p>

			<p>You get the drift</p>

			<p>Wait, you get the drift is not the wisdom they were propagating. We mean you get the drift about the kind of wisdom they were propagating.</p>
			<p>So this is it. Here we are in the year 2000 something (can't write the exact date, God knows when this section will get updated again) and the happily unmarried company continues to sell fun, packed neatly in little brown boxes. We organise music festivals and have a little thing going on facebook as well.</p>

			<p>To know more about us perhaps the text below may be of some use.</p>

			<p>Happily Unmarried was anti established in 2003 with no vision and no business plan. Actually at some point we did make a business plan but according to that we should have retired 5 years ago.</p>

			<p>We make fun products, we do music festivals, we work with corporates when they want to do interesting work and lately we have been doing a lot of projects involving branding, communication, interiors, marketing all rolled into one.</p>

			<p>This online site is to provide you a simpler, more meaningful consumer experience. Before you say, hold on guys this is just an e-commerce website and not a self help book, we say <a href="<?php echo $this->getUrl(); ?>">click here</a> and start shopping.</p>

			<div class="collapse_accordion">
				<div class="cms_accordion_toggle_up_arrow"></div>
			</div>
		</div>

		<h2>HUHQ</h2>
		<div class="matter">

			<img class="f-left w-40" src="<?php echo $this->getSkinUrl('images/about_us/HUWM---About-Us---Open_11.png') ?>" alt=""/>

			<h3>Welcome To HUHQ!</h3>

			<p>The first thing that you notice about our office is that it is not sea facing which should not surprise you because we are based out of Delhi.We took the strategic decision of shifting to Okhla phase 2 because the old basement we worked out of in shahpurjat was begining to feel kinda small.(please note this is perhaps the only time in the entire website where we have used strategic and decision in the same sentence).</p>

			<p>For those who don't know, Okhla is the most advanced and well planned industrial estate in Delhi. For those who know well their is no point in lying to you since you know already! All those who manage to reach our office without calling atleast thrice, we salute you. All those who tried and failed to reach, we understand.</p>

			<img class="w-90 ml-10 y-10" src="<?php echo $this->getSkinUrl('images/about_us/about-us-beer-glasses.png') ?>" alt=""/>

			<h3>How To Reach?</h3>

			<p><strong>For the responsible:</strong><br> Choose the Metro, just <a href="http://www.youtube.com/watch?v=d52SGKl0po8" target="_blank">click here</a>.</p>

			<p>
				<strong>For the courageous:</strong>
				<br> Happily Unmarried Marketing Pvt Ltd.
				<br> A-48, FIEE Complex
				<br> Okhla Industrial Area, Phase 2
				<br> New Delhi - 110020, India
			</p>

			<div class="collapse_accordion">
				<div class="cms_accordion_toggle_up_arrow"></div>
			</div>
		</div>

		<h2>Media</h2>
		<div class="matter">

			<img class="f-left w-20" src="<?php echo $this->getSkinUrl('images/about_us/HUWM---About-Us---Open_15.png') ?>" alt=""/>

			<p>Thank you Journalists, bloggers, media people, trend watchers, channels etc for covering us. We will always strive to create better products and do stuff which makes our products cover worthy. And sometimes we may not be able to send you hi-res pictures
			in time, we may not agree with the story line you are working on but we truly appreciate you taking that extra effort to locate and chase us.</p>

			<img class="w-100" src="<?php echo $this->getSkinUrl('images/cmspages/media-img2.jpg') ?>" alt=""/>
			<div class="contains_floats">
				<img class="f-left no-margin w-30" src="<?php echo $this->getSkinUrl('images/cmspages/media-img3.jpg') ?>" alt=""/>
				<img class="f-right no-margin w-68" src="<?php echo $this->getSkinUrl('images/cmspages/media-img4.jpg') ?>" alt=""/>
			</div>

			<p>We insist on getting questions on email cause it gives us time to do a search on the meanings of some of the terms asked. We usually do not know what most of the fancy design terms mean. But we know that we are not KITSCH.</p>

			<div class="contains_floats">
				<img class="f-left no-margin w-30-5" src="<?php echo $this->getSkinUrl('images/cmspages/media-img5.jpg') ?>" alt=""/>
				<img class="f-right no-margin w-68" src="<?php echo $this->getSkinUrl('images/cmspages/media-img6.jpg') ?>" alt=""/>
			</div>

			<div class="collapse_accordion">
				<div class="cms_accordion_toggle_up_arrow"></div>
			</div>
		</div>

		<!-- <h2>Videos</h2>
		<div class="matter">

		</div> -->

		<h2>Music in the Hills</h2>
		<div class="matter has_slider">

			<div class="horizontal-4 contains_floats">
				<img src="<?php echo $this->getskinUrl('images/about_us/HUWM---About-Us---Open_18.png')?>" alt=""/>
				<img src="<?php echo $this->getskinUrl('images/about_us/HUWM---About-Us---Open_20.png')?>" alt=""/>
				<img src="<?php echo $this->getskinUrl('images/about_us/HUWM---About-Us---Open_22.png')?>" alt=""/>
				<img src="<?php echo $this->getskinUrl('images/about_us/HUWM---About-Us---Open_24.png')?>" alt=""/>
			</div>
			<div>
				<p>Music in the hills is our annual festival of live music, we do it in partnership with Parikrama. MiH has no agenda except to bring together good music, good listeners and exotic locations. We have had 8 so far and India's best bands have performed at Music in the hills. MiH is also the longest running independent music festival.</p>
			</div>

			<div class="y-20">
				<ul class="slider">
					<li>
						<img class="w-100" src="<?php echo $this->getSkinUrl('images/cmspages/music-slider-img1.jpg'); ?>" alt=""/>
					</li>
					<li>
						<img class="w-100" src="<?php echo $this->getSkinUrl('images/cmspages/music-slider-img2.jpg'); ?>" alt=""/>
					</li>
					<li>
						<img class="w-100" src="<?php echo $this->getSkinUrl('images/cmspages/music-slider-img3.jpg'); ?>" alt=""/>
					</li>
					<li>
						<img class="w-100" src="<?php echo $this->getSkinUrl('images/cmspages/music-slider-img4.jpg'); ?>" alt=""/>
					</li>
				</ul>
			</div>

			<p>To know more <a href="<?php echo $this->getUrl('mih.html'); ?>">click here!</a></p>

			<div class="collapse_accordion">
				<div class="cms_accordion_toggle_up_arrow"></div>
			</div>
		</div>

		<h2>Contact Us</h2>
		<div class="matter">

			<div>

				<img class="f-left w-30" src="<?php echo $this->getSkinUrl('images/about_us/HUWM---About-Us---Open_31.png'); ?>" alt=""/>

				<p>It will be our pleasure to receive any query from you because you are a customer and customer is more important than chilled beer.</p>

				<p>At least between 10am and 6pm.</p>

				<span>For Order related queries contact us at:</span><br/>
				Email - <a href="mailto:info@happilyunmarried.com">info@happilyunmarried.com</a><br/>
				Phone - 011 - 41042266 <br/><br/>

				<span>For Retail enquiries contact us at:</span><br/>
				Email - <a href="mailto:deepa@happilyunmarried.com">deepa@happilyunmarried.com</a><br/>
				Phone - +91-8800402266<br/><br/>

				<span>For e-commerce Retail enquiries contact us at:</span><br/>
				Email - <a href="mailto:manish@happilyunmarried.com">manish@happilyunmarried.com</a><br/>
				Phone - +91-9818066636<br/><br/>

				<span>For Franchise enquiries contact us at:</span><br/>
				Email - <a href="mailto:rajat@happilyunmarried.com">rajat@happilyunmarried.com</a><br/>
				Phone - +91-9810296994<br/><br/>

				<span>For Corporate enquiries contact us at:</span><br/>
				Email - <a href="mailto:abhijit@happilyunmarried.com">abhijit@happilyunmarried.com</a><br/>
				Phone - +91-8527322155<br/><br/>

				<p>Or you can make our day and actually write to us at -</p>

				<p>
					Happily Unmarried Marketing Pvt Ltd<br/>
					A - 48, FIEE, Okhla Industrial Area, Phase - 2<br/>
					New Delhi - 110020<br/>
					India<br/>
				</p>

			</div>
			<div>
				<span>Or if you want to come meet us (at your own risk)- <a href="http://www.youtube.com/watch?v=d52SGKl0po8" target="_blank">click here!</a><br/></span>
			</div>

			<div class="collapse_accordion">
				<div class="cms_accordion_toggle_up_arrow"></div>
			</div>
		</div>

	</div>

</div>

<div class="keep_shopping_box y-20 wrapper-96">
	<a href="<?php echo $this->getBaseUrl(); ?>" class="button green">Keep Shopping</a>
</div>

<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/jquery.bxslider.css') ?>" />
<script src="<?php echo $this->getSkinUrl('js/jquery.bxslider.min.js') ?>"></script>

<script type="text/javascript">
jQuery(document).ready(function($) {
	$('.slider').hide();

	$('.accordion').accordion({
		heightStyle: "content",
		collapsible: true,
		activate: function(event, ui) {
			if(ui.newPanel.context.textContent == "Music in the Hills") {
				call_slider();
			}
		}
	});

	$('.collapse_accordion').click(function() {
		$(this).parent().prev().click();
	});

	function call_slider() {
		$('.slider').show();
		$('.slider').bxSlider({
			pager: true,
			controls: false
		});
	}
});
</script>
