<div class="cms-subcategory-area">
	<ul>
		<li class="current">
			<a href="#intern" class="intern">
				<div class="circle">&nbsp;</div>
				Interns
			</a>
		</li>
		<li>
			<a href="#work-for-us" class="work-for-us">
				<div class="circle">&nbsp;</div>
				Work for us
			</a>
		</li>
	</ul>
</div>

<div class="cms-inner-page-content-area">
	<div class="inner-content-area" id="intern">
		<h1 class="content-page-title intern">Interns</h1>
		<div class="inner-simple-content-area"><img class="cms-thumb-imgsty" src="http://hu.iksuladev.com/hulive/skin/frontend/happy/default/images/cmspages/careers-intern.jpg" alt="">
			<p style="margin-top: 33px;">We believe that no organisation can function without interns. They are the building blocks of the future (and also the ones who do all the jobs which no one else wants to). We take our internship programme very seriously and some of the best work that has happened in our company has been done by Interns.</p>
		</div>
		<div class="inner-simple-content-area text-align-sty"><img src="http://hu.iksuladev.com/hulive/skin/frontend/happy/default/images/cmspages/careers-img.jpg" alt=""></div>
		<div class="inner-simple-content-area">
			<p><strong class="cms-subtitle">We would like to offer a bit of advice to all interns who apply.<br> Read this only if you are genuinely interested in interning with us.</strong></p>
			<ul>
				<li>1) Please do not name your portfolio, "portfolio.pdf", we get some many portfolio.pdf files every day that it is now impossible to keep a tab. Show us how creative you can be by giving your work a very wicked name.(please do not name it the 3 mistakes of my life, someone has done that already)</li>
				<li>2) If any resume begins with the following or anything similar sounding we do not read it:<br><br> I wish to contribute meaningfully<br><br> I am committed to excellence<br><br> I co-relate organisational goals with mine<br><br> I am a team player, hard working and sincere<br><br> I wish to begin my journey into the corporate world....<br><br> I believe self growth leads to organisational growth just like every river leads to an ocean<br><br> ..... If you are applying to us keep it brief and interesting and avoid the cliches.</li>
				<li>3) Your ideas and originality needs to reflect in everything you send us, a single paragraph is enough if it tells us how good you are.</li>
				<li>4) Two months is too little a time period, Come for 3 or 4 months or even more.</li>
				<li>5) we offer internships in Delhi only but it may involve an all expense paid trip to places like Bali, Goa, New York and London to chill out between projects.        
					<ul>
						<li>5 a)    Sorry printing error read the above as We offer internships in Delhi only and it will involve travel in public transport to places like            Moradabad,Panipat, Kucha pati ram, sadar bazar and other places where no intern in your batch has ever been before.</li>
					</ul>
				</li>
				<li>6) Please please do not come with your parents, we understand they can be concerned and would want to see the office (ha ha we mean the warehouse). If they were half unsure with our name we promise you they will never let you intern if they see the office (ware house).</li>
				<li>7) You can be brilliant but there is a distinct possibility that your style may not match ours or we may not understand "your work" or your thought process at all. please don't take offence. If we say no.</li>
				<li>8) We do not pay our interns too much money and occasionally we borrow from them.</li>
				<li>9) All interns get to travel free to Music in the Hills, our music fest.<br><br> (fine print: where they have to work very hard but also enjoy like no one else can).</li>
				<li>10) Take nothing seriously even the stuff you just read here.<br><br> We accept interns of all shapes and sizes in all departments be it design, marketing, ecommerce, events etc.<br><br><br> If you are enthusiastic and can work long hours get in touch  :  <a href="mailto:careers@happilyunmarried.com" class="=&quot;career-link&quot;">careers@happilyunmarried.com</a> </li>
			</ul>
		</div>
	</div>
	<div class="inner-content-area" id="work-for-us">
		<h1 class="content-page-title work-for-us">Work for Us</h1>
		<img class="cms-thumb-imgsty1" src="http://hu.iksuladev.com/hulive/skin/frontend/happy/default/images/cmspages/careers-work-for-us.jpg" alt="">
		<p>We work with lots of designers on a project and royalty basis. Till now we have worked with over 35 designers from leading design schools. The good bit is that some of the people who end up designing for us are not trained to be designers, they just have a lot of crazy ideas and we help them implement. it.</p>
		<p class="cms-subtitle">We would recommend the following before you write to us:</p>
		<p>Check our website and identify the products you like and buy them (ok that was a joke).<br><br> If you have a product idea in mind then just shoot us a mail without any inhibitions.If we like your idea we will get back to you.<br><br> If you are a design firm with manufacturing capabilities then it is even better as that takes the production load off our back.<br><br> The design fee is a part advance and part royalty on actual sale.<br><br> To share your ideas send us a mail at <a href="mailto:design@happilyunmarried.com" class="career-link">design@happilyunmarried.com.</a></p>
	</div>
	<div class="keep_shopping_box" style="margin-bottom:30px;">
		<a href="<?php echo $this->getBaseUrl(); ?>" class="happy_button keep_shopping_button">Keep Shopping</a>
	</div>
</div>

<script src="<?php echo $this->getSkinUrl('js/') ?>jquery.scrollTo.js"></script>
<script src="<?php echo $this->getSkinUrl('js/') ?>jquery.nav.cms.page.js"></script>
<script>
jQuery(document).ready(function($) {
	$('.cms-subcategory-area').onePageNav({
		scrollOffset: 90,
		easing: 'swing',
		scrollSpeed: 1200
	});
});
</script>