<?php Mage::getSingleton('core/session')->setCurrentCategory($this->getCategoryId()); ?>
<?php echo $this->getChildHtml('category_header'); ?>
<?php $currentCategoryname = Mage::getModel('catalog/category')->load($this->getCategoryId());?>

<?php $_category = Mage::getSingleton('catalog/layer')->getCurrentCategory(); ?>
<?php $_categoryId = $_category->getId(); ?>
<?php $searchString = $this->helper('explore')->checkAndReturnSearchString(); ?>


<script type="text/javascript">
/*var productList = {};

function onProductClick(element) {
    var productId = jQuery(element).parent().attr('id');
    productId = parseInt(productId.replace('product_id_', ''));

    ga('ec:addProduct', productList[productId]);
    ga('ec:setAction', 'click', { list: "<?php echo $currentCategoryname->getData('name'); ?>" });
    ga('send', 'event', 'UX', 'click', 'Results', {
        'hitCallback': function() {
            document.location = jQuery(element).attr('href');
        }
    });
}*/
</script>


<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>

    <div class="category-products">

        <?php // Grid Mode ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>

        <ul class="products-grid" id="<?php echo 'container' . $_categoryId; ?>">
            <?php $product_counter = 1; ?>
            <?php $i=0; foreach ($_productCollection as $_product): $i++; ?>

                <li class="item" id="product_id_<?php echo $_product->getId(); ?>">

                    <a href="<?php echo $_product->getProductUrl() . $searchString ?>">

                        <div class="product-image" id="<?php echo 'product_' . $_product->getId(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <img class="item-image" src="<?php echo $this->getSkinUrl('images/homepage/lazyloader_placeholder.png') ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <noscript>
                                <img class="item-image" src="<?php echo $this->getSkinUrl() . 'images/homepage/lazyloader_placeholder.png' ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </noscript>
                        </div>

                        <h2 class="product-name">
                                <?php $name = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                <?php $thresholdSize = 20; ?>
                                <?php $nameLength = strlen($name); ?>
                                <?php $title = 0; ?>
                                <?php if($nameLength > $thresholdSize) { $name = substr($name, 0, ($thresholdSize - 1)) . '...'; $title = 1; } ?>
                            <span class="product_name_title" <?php if($title == 1): ?>title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"<?php endif; ?>>
                                <?php echo $name ?>
                            </span>
                        </h2>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </a>

                </li>
                <script type="text/javascript">
/*
                    var productId = parseInt("<?php echo $_product->getId(); ?>");

                    productList[productId] = {
                        'id': '<?php echo $_product->getSku(); ?>',
                        'name': '<?php echo str_replace("'", "\\'", $_product->getName()); ?>',
                        'category': "<?php echo $currentCategoryname->getData('name');?>",
                        'brand': '<?php echo "Happily Unmarried"; ?>',
                        'variant': '<?php "" ?>',
                        'list': "<?php echo $currentCategoryname->getData('name');?>",
                        'position': '<?php echo $product_counter; ?>'
                    };
                    
                    ga('require', 'ec');
                    ga('ec:addImpression', productList[productId]);
                    ga('send', 'pageview');
*/
                </script>

                <?php $product_counter = $product_counter+1; ?>
            <?php endforeach; ?>

        </ul>

    </div>

<?php endif; ?>
<?php echo $this->getChildHtml('product_list_toolbar');?>
