<?php $_code = $this->getMethodCode(); ?>

<div class="input-box display-none payment-data-box" id="p_method_<?php echo $_code ?>_data">
    <p class="paytm-mm">
    	 <img src="<?php echo $this->getSkinUrl('images/Paytm-Logo-Heading.png'); ?>"/>
    </p>

    <?php echo Mage::helper('paytm')->__('You will be redirected to PAYTM Payment Gateway when you place an order.') ?>
    
    <div class="checkout-final-button">
        <button type="submit"  id="place-order" class="button happy_button" onclick="checkout.save(); return false;"><?php echo $this->__('Pay Securely') ?></button>
    </div>
</div>
