<div class="mih_content_area">
		<div class="mih_content_innerarea" style="padding-bottom:0px;">
			<div class="include_content">
				THIS INCLUDES
				<ul>
					<li>Stay		(Both Days)</Li>
					<li>Food		(Breakfast, Luch and Dinner)</Li>
					<li>Music	(From arrival till departure)</Li>
					<li>Fun		(The moment you book)</Li>
				</ul>
			</div>
			<div class="include_content include_content_no_border">
				DOES NOT INCLUDE
				<ul>
					<li>Travel to or from Mandawa</li>
					<li>Additional activities undertaken around the place</li>
					<li>Additional food ordered</li>
				</ul>
			</div>
		</div>

		<div class="mih_content_innerarea include_content_no_border" >
			<h2 class="content-page-title1">TERMS AND CONDITIONS</h2>		
			<p>1. Bookings are on a first come first serve basis.</p>
			<p>2. The Tariffs are special offers available till 15th November, 2013.</p>
			<p>3. Allotment of rooms is purely on our discretion. Preference is given to guests who have attended any previous MiH or have booked early.</p>
			<p>4. No Drugs.</p>
			<p>5. Artists are subject to final confirmation and may change without prior notice.</p>
			<p>6. The Organizers are not liable in the case of the Force Majeure.</p>
			
			<h2 class="content-page-title1">CANCELLATION AND REFUND POLICY</h2>		
			<p>1. No refund in case of cancellation after 15th November 2013. </p>
			<p>2. 10% cancellation charges in all other cases.</p>

		</div>
</div>