<li id="remember-me-box" class="control">
    <?php $rememberMeId = 'remember_me' . Mage::helper('core')->getRandomString(10); ?>
    <div class="input-box no-display">
        <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Remember Me') ?>" />
    </div>
    <label for="<?php echo $rememberMeId; ?>" class="checkbox checked" onClick="jQuery(this).toggleClass('checked');"><?php echo $this->__('Remember Me') ?></label>
</li>
