<?php echo $this->getChildHtml('folofo_head'); ?>

<div class="one_category" id="folofo_cms_page_container">

	<div class="folofo_section">
		<h2 class="large_slim_heading" id="folofo_cms_heading_1">About Us</h2>
		<?php echo $this->getChildHtml('folofo_about_us_block'); ?>
	</div>

	<div class="folofo_section">
		<h2 class="large_slim_heading" id="folofo_cms_heading_2">Partners</h2>
		<?php echo $this->getChildHtml('folofo_partners_block'); ?>
	</div>

	<!-- <div class="folofo_section">
		<h2 class="large_slim_heading" id="folofo_cms_heading_3">Videos</h2>
		<?php // echo $this->getChildHtml('folofo_videos_block'); ?>
		<div class="cms-video-area">
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
		</div>
		<div class="cms-video-area">
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
			<div class="cms-video-thumb-content-area">
				<div class="cms-video-thumb-area">
					<a href=""><img src="<?php // echo $this->getSkinUrl('images/cmspages/') ?>video-thumb.jpg"></a>
				</div>
				<div class="cms-video-content-area">
					<h1>Video Title</h1>
					<p>Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. Body copy. </p>
				</div>
			</div>
		</div>
	</div> -->

</div>
