<?php if (!$methods = $this->getMethods()) : ?>

    <p><?php echo $this->helper('checkout')->__('Sorry, no quotes are available for this order at this time.') ?></p>

<?php else : ?>

    <?php //if($_code = $this->getSelectedMethodCode()): echo 'bummer ' . $_code; endif; ?>

    <div id="review-please-wait" style="display: none;">
        <div>
            <img src="<?php echo $this->getSkinUrl('images/simple_loader_white.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </div>
    </div>

    <h2 class="opc_title">SELECT PAYMENT METHOD</h2>

    <div class="methods-right-panel">

        <dl class="sp-methods">

            <?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>

                <dt class="sp-method-dt">
                <?php if( sizeof($this->getMethods()) > 1 ): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />

                    
                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                <?php endif; ?>
                    <label for="p_method_<?php echo $_code ?>"><?php echo $this->htmlEscape($_method->getTitle()) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
                </dt>

                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                <dd class="sp-method-dd-for-<?php echo $_code; ?>">
                    <?php echo $html; ?>
                </dd>
                <?php endif; ?>

            <?php endforeach; ?>

        </dl>

    </div>

<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
//]]>
</script>
<?php endif; ?>

