<style type="text/css">
	.header-container
	{
		*left:0px;
	}
	.left_categories_floater,.block block-cart
	{
		z-index:1000;
		
	}
	
	.nivoSlider
	{
		overflow:inherit !important;
	}
	
	.nivoSlider img
	{
		height:300px !important;
		width:900px !important;
	}

	.header
	{
		background-color: #fff;
		display: block;
		height: 80px;
		margin: 0 auto;
		padding: 10px;
		position: relative;
		text-align: right;
		width: 930px;
		z-index: 10;
	}
	
	.col-main
	{
		height:auto !important;
		position:relative !important;
	}
	
	.left_categories_floater
	{
		/*position:absolute !important;*/
		left:inherit !important;
		left:0px !important;
	}
	
	.block-cart
	{
		/*position:absolute !important;*/
		margin-left: 600px;
		right:inherit !important;
		right:20px !important;
	}
	
	/*Content Slider*/
p,
ul {
  margin: 0;
  padding: 0;
}
p {
  margin-bottom: 20px;
}
#nav1 {
  list-style: none;
}
#nav1 li {
  margin-bottom: 2px;
}

#nav1 a {
  background: #ededed;
  color: #666;
  display: block;
  font-size: 11px;
  padding: 5px 10px;
  text-decoration: none;
  text-transform: uppercase;
}
#nav1 a:hover {
  background: #dedede !important;
}
#nav1 li.current1 a {
  background: #666 !important;
  color: #ededed !important;
}
.current1 {
  background-color: red !important;
}
#container12 {
  margin: 0 auto;
  width: 900px;
}
.section {
  border-bottom: 5px solid #ccc;
  padding-bottom:20px;

}
.section p:last-child {
  margin-bottom: 0;
}

div.section-header {
   background: lightblue;
   height: 100px;
   width:900px;
}

div.section-container {
   height:auto;

}

.catContent
{
	margin-top:10px;

}

#md_quickview_handler
{
	z-index:10000;
}

/*-- Filter Stylesheet --*/
.info {
float:left;
width:100%;
margin:20px 0;
padding-bottom:20px;
border-bottom:1px solid #353535;
color:#fff;
position:relative;
}

.info h1 {
font-family:'Playball', serif;
font-size:77px;
font-weight:normal;
margin:0;
margin-bottom:20px;
}

.info p {
float:left;
margin:0;
margin-bottom:6px;
}

.info .demo {
position:absolute;
top:45px;
right:0;
}

.info .demo a {
display:inline-block;
margin-left:10px;
font-weight:bold;
}

.dd {
float:left;
clear:both;
width:960px;
padding:20px;
padding-bottom:10px;
margin:0;
margin-bottom:20px;
background:#ddd;
background:rgba(255, 255, 255, .8);
color:#222;
}

.footer {
float:left;
clear:both;
width:100%;
text-align:center;
font-size:10px;
text-transform:uppercase;
padding:20px 0;
margin-top:20px;
border-top:1px solid #353535;
}

/* ------ filtrey
-----------------------------------------------*/

.filters {
float:left;
clear:both;
width:1000px;
}

.filters .filter {
float:left;
clear:both;
width:960px;
padding:20px;
margin-bottom:20px;
background:#545454;
background:rgba(255, 255, 255, .1);
}

.filters .filter a {
float:left;
display:block;
padding:5px;
margin-right:20px;
font-size:11px;
text-transform:uppercase;
outline:none;
}

.filters .filter .active {
background:#eee;
color:#111;
}

.filters .container {
float:left;
clear:both;
width:100%;
position:relative;
}

.filters .container ul,
.filters .container ul li {
display:block;
list-style:none;
padding:0;
margin:0;
}

.filters .container ul li {
float:left;
margin:0 8px 8px 0;
font-size:0;
line-height:0;
}

.filters .container a {
display:block;
float:left;
width:192px;
height:192px;
}

	
</style>
<!--<script src="<?php //echo $this->getSkinUrl('js/jquery.js')?>"></script>-->
<script src="<?php echo $this->getSkinUrl('js/jquery.scrollTo.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery.nav.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/jquery_002.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/filters.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/init.js')?>"></script>
<script>
// jQuery(document).ready(function() {
 
  jQuery('#nav1').onePageNav({
    scrollOffset: 110,
    begin: function() {
	   console.log('start');
    },
    end: function() {
	   console.log('stop');
    }
  });
  
  
  
// });
</script>



<!-- RK COntent JS -->
<div id="container12">
  <div class="section section-container"> 
   <div style="position: fixed;top:100px;height:0px;" class="section-header"></div>	
		
        
<!-- Harpreet Slider -->


<?php $harpreet = $this->helper('harpreet_slider/config'); ?>
<?php $design = $harpreet->getDesign(); ?>
<?php $animation = $harpreet->getAnimation(); ?>
<?php $event = $harpreet->getEvent(); ?>

<div class="harpreet-slider-block">
    <div class="slider-wrapper" style="width:100%; height:300px;"><!--<?php //echo $design['width'] . $design['height'] ?> position:absolute; left:0;-->
        <div id="slider" class="nivoSlider" style="height:300px;" ><!--<?php// echo $design['height'] ?>-->
            <?php $_counter = 0 ?>
            <?php foreach ($harpreet->getSliders() as $_slider) : ?>
                <a href="<?php echo $_slider['link'] ?>">
                    <img src="<?php echo $_slider['image'] ?>" <?php if ($design['texten'] == 1) : ?>title="#harpreet-elem<?php echo $_counter ?>"<?php endif; ?> />
                </a> 
                <?php $_counter++ ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php $_counter = 0 ?>
    <?php foreach ($harpreet->getSliders() as $_slider) : ?>
        <div id="harpreet-elem<?php echo $_counter ?>" class="nivo-html-caption">
            <?php echo $_slider['title'] ?>
        </div>
        <?php $_counter++ ?>
    <?php endforeach; ?>
</div>

<style>
    .nivo-caption, .nivo-caption *{
        <?php echo $design['textscolor']; ?>
    }
    .nivo-caption{
        <?php echo $design['bgscolor']; ?>
        <?php echo $design['textopacity']; ?>
        <?php echo $design['textpos']; ?>
        <?php echo $design['textsize']; ?>
    }
    
    .nivo-controlNav a{
        <?php echo $design['buttonscolor']; ?>
    }
    .nivo-controlNav a.active, .nivo-controlNav a:hover{
        <?php echo $design['buttonscolorhover']; ?>
    }
    .nivo-controlNav{
        <?php echo $design['buttonpos']; ?>
    }
    .nivo-nextNav{
        <?php echo $design['nextimage']; ?>
    }
    .nivo-prevNav{
        <?php echo $design['previmage']; ?>
    }
</style>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#slider').nivoSlider({
            effect: '<?php echo $animation['type'] ?>',
            slices: <?php echo $animation['slices'] ?>,
            boxCols: <?php echo $animation['boxcols'] ?>,
            boxRows: <?php echo $animation['boxrows'] ?>,
            animSpeed: <?php echo $animation['speed'] ?>,
            pauseTime: <?php echo $animation['pausetime'] ?>,
            startSlide: 0,
            directionNav: <?php echo $design['nextpreven'] ?>,
            controlNav: <?php echo $design['buttonen'] ?>,
            controlNavThumbs: false,
            pauseOnHover: <?php echo $animation['hover'] ?>,
            manualAdvance: false,
            prevText: 'Prev',
            nextText: 'Next',
            randomStart: false,
            beforeChange: function(){<?php echo $event['beforechange'] ?>},
            afterChange: function(){<?php echo $event['afterchange'] ?>},
            slideshowEnd: function(){<?php echo $event['slideshowEnd'] ?>},
            lastSlide: function(){<?php echo $event['lastSlide'] ?>},
            afterLoad: function(){<?php echo $event['afterLoad'] ?>}
        });
		jQuery('.section-container').stickyHeader({stickyClass : 'section-header'});
    });
</script>

<!-- Harpreet Slider End -->

   
  </div>
  
  
  <div class="section section-container" id="3">  	  
    <div style="position: static;top:auto;" class="section-header">
        Header 1
        
    </div>
    <div style="float:left;" class="extradiv"></div>
    <div class="catContent">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   	</div>
  </div>

  <div class="section section-container" id="4">
  	<div style="position: static;top: auto;" class="section-header">
        Header 2
      </div>
   <div class="catContent">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   	</div>
  </div>

  <div class="section section-container" id="7">
  <div style="position: static;top: auto;" class="section-header">
        Header 3
      </div>
 <div class="catContent">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   	</div>
   
  </div>

  <div class="section section-container" id="8">
  <div style="position: static;top: auto;" class="section-header">
        Header 4
      </div>
  <div class="catContent">
    <div class="filters demo1">
		<div class="filter">
				<a href="#" rel="city">City</a>
				<a href="#" rel="cars">Cars</a>
				<a href="#" rel="other">Other</a>
				<a href="#" rel="all">All</a>
			</div>
			<div class="container">
				<ul>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img1.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img6.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img5.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img7.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img3.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img4.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img8.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img2.jpg')?>" alt="" /></a>
					</li>
					<li class="other">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img10.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img12.jpg')?>" alt="" /></a>
					</li>
				</ul>
			</div>
		</div>
	
  </div>
  </div>

  <div class="section section-container" id="9">
  <div style="position: static;top: auto;" class="section-header">
        Header 5
      </div>
    <strong>Section 4</strong>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu
  </div>
</div>

<!-- RK Content JS End-->




