<!-- Harpreet Slider -->

<?php $harpreet = $this->helper('harpreet_slider/config'); ?>
<?php $design = $harpreet->getDesign(); ?>
<?php $animation = $harpreet->getAnimation(); ?>
<?php $event = $harpreet->getEvent(); ?>

<div class="harpreet-slider-block">
    <div class="slider-wrapper">
        <div id="slider" class="nivoSlider" >
            <?php $_counter = 0 ?>
            <?php foreach ($harpreet->getSliders() as $_slider) : ?>
                <a href="<?php echo $_slider['link'] ?>">
                    <img src="<?php echo $_slider['image'] ?>" <?php if ($design['texten'] == 1) : ?>title="#harpreet-elem<?php echo $_counter ?>"<?php endif; ?> />
                </a>
                <?php $_counter++ ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php $_counter = 0 ?>
    <?php foreach ($harpreet->getSliders() as $_slider) : ?>
        <div id="harpreet-elem<?php echo $_counter ?>" class="nivo-html-caption">
            <?php echo $_slider['title'] ?>
        </div>
        <?php $_counter++ ?>
    <?php endforeach; ?>
</div>

<style>
    .nivo-caption, .nivo-caption *{
        <?php echo $design['textscolor']; ?>
    }
   .nivo-caption { text-align: center; font-family: Roboto !important; -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=70)" !important; filter: alpha(opacity=70) !important; background-color: #ffffff; opacity: 0.7; -moz-opacity: 0.7; filter: alpha(opacity=7); left: 0; bottom: 0; width: 100%; min-height: 41px; height: auto; text-transform: uppercase; }

    .nivo-controlNav a{
        <?php //echo $design['buttonscolor']; ?>
    }
    .nivo-controlNav a.active, .nivo-controlNav a:hover{
        <?php //echo $design['buttonscolorhover']; ?>
    }
    .nivo-controlNav{
        <?php echo $design['buttonpos']; ?>
    }
    .nivo-nextNav{
        <?php echo $design['nextimage']; ?>
    }
    .nivo-prevNav{
        <?php echo $design['previmage']; ?>
    }
    .my_current_cover_id {
        display: none;
    }
</style>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#slider').nivoSlider({
            effect: '<?php echo $animation['type'] ?>',
            slices: <?php echo $animation['slices'] ?>,
            boxCols: <?php echo $animation['boxcols'] ?>,
            boxRows: <?php echo $animation['boxrows'] ?>,
            animSpeed: <?php echo $animation['speed'] ?>,
            startSlide: 0,
            directionNav: true,
            controlNav: <?php echo $design['buttonen'] ?>,
            controlNavThumbs: false,
            pauseOnHover: false,
            manualAdvance: true,
            prevText: 'Prev',
            nextText: 'Next',
            randomStart: false,
            beforeChange: function(){<?php echo $event['beforechange'] ?>},
            afterChange: function(){<?php echo $event['afterchange'] ?>},
            slideshowEnd: function(){<?php echo $event['slideshowEnd'] ?>},
            lastSlide: function(){<?php echo $event['lastSlide'] ?>},
            afterLoad: function(){<?php echo $event['afterLoad'] ?>},
			pauseTime: <?php echo $animation['pausetime'] ?>
        });
    });
</script>

<!-- Harpreet Slider End -->
