
<?php $_category = Mage::getSingleton('catalog/layer')->getCurrentCategory(); ?>
<?php $_categoryId = $_category->getId(); ?>
<?php $searchString = $this->helper('explore')->checkAndReturnSearchString(); ?>

<script type="text/javascript">
/*var productList = {};

function onProductClick(element) {
    var productId = jQuery(element).parent().attr('id');
    productId = parseInt(productId.replace('product_id_', ''));

    ga('ec:addProduct', productList[productId]);
    ga('ec:setAction', 'click', { list: "<?php echo $_category->getName(); ?>" });
    ga('send', 'event', 'UX', 'click', 'Results', {
        'hitCallback': function() {
            document.location = jQuery(element).attr('href');
        }
    });
}*/
</script>

<?php
    $_cat = new Mage_Catalog_Block_Navigation();
    $curent_cat = $_cat->getCurrentCategory();
    $category_ids = $_cat->getCurrentCategory()->getParentCategory()->getPath();
    $cat_id = explode('/',$category_ids);
    $top_parent_id = $cat_id[3];
    $top_parent_model_id = $cat_id[4];

    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');

 ?>

<?php
    $bannerExists = false;
    if($_category->getImageUrl() && ($_category->getImageChooser() == 1 || $_category->getImageChooser() == 2)) {
        $bannerExists = true;
    }
?>

<?php
   $_categorypar = Mage::getModel('catalog/category')->load($top_parent_id);
?>

<?php if($_categorypar['featured_category_parent'] != 1){?>

<?php if(1): ?>
    <div style="display:none;">
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('hupopup/index.phtml')->toHtml();?>
    </div>
<?php endif;?>

<?php if(!$_productCollection->count()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

<?php else: ?>
    <div class="category-products<?php if(!$bannerExists): echo ' dynamic_category_header_compensation'; endif; ?>">

        <?php // Grid Mode ?>
        <?php $_collectionSize = $_productCollection->count();?>
        <?php $_columnCount = $this->getColumnCount(); ?>

        <ul class="products-grid" id="<?php echo 'container' . $_categoryId; ?>">
            <?php $product_counter = 1; ?>
            <?php $i=0; foreach ($_productCollection as $_product): $i++; ?>

                <li class="item<?php if($i % 3 == 2): echo ' middle'; elseif($i % 3 == 1): echo ' first'; endif; ?>" id="product_id_<?php echo $_product->getId(); ?>">

                    <a href="<?php echo $_product->getProductUrl() . $searchString ?>">

                        <div class="product-image" id="<?php echo 'product_' . $_product->getId(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <img class="item-image" src="<?php echo $this->getSkinUrl() . 'images/homepage/lazyloader_placeholder.png' ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <noscript>
                                <img class="item-image" src="<?php echo $this->getSkinUrl() . 'images/homepage/lazyloader_placeholder.png' ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </noscript>
                        </div>

                        <h2 class="product-name">
                                <?php $name = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                <?php $thresholdSize = 20; ?>
                                <?php $nameLength = strlen($name); ?>
                                <?php $title = 0; ?>
                                <?php if($nameLength > $thresholdSize) { $title = 1; } ?>
                            <span class="product_name_title" <?php if($title == 1): ?>title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"<?php endif; ?>>
                                <?php echo $name ?>
                            </span>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </h2>
                        <p class="product-short-desc">
                            <?php echo strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')) ?>
                        </p>
                    </a>
                </li>

                <script type="text/javascript">

                   /* var productId = parseInt("<?php echo $_product->getId(); ?>");


                    productList[productId] = {
                        'id': '<?php echo $_product->getSku(); ?>',
                        'name': '<?php echo str_replace("'", "\\'", $_product->getName()); ?>',
                        'category': '<?php echo $_category->getName(); ?>',
                        'brand': '<?php echo "Happily Unmarried"; ?>',
                        'variant': '<?php '' ?>',
                        'list': '<?php echo $_category->getName(); ?>',
                        'position': '<?php echo $product_counter; ?>'
                    };

                    ga('require', 'ec');
                    ga('ec:addImpression', productList[productId]);
                    ga('send', 'pageview');*/
                </script>

                <?php $product_counter = $product_counter+1; ?>
            <?php endforeach; ?>
        </ul>

    </div>


<?php endif; ?>

<?php }else{ ?>



<div class="wrap_cover">

    <div class="container_cover">

        <!--Filter-->
        <div class="middle_content_cover">

            <div class="search_cover">

                <h1><?php echo $this->__('Find all designs available for your phone!') ?></h1>

                <div class="search_form_cover">

                    <form>

                        <div class="search_wrap">

                            <div class="brands_wrap">

                                <select name="brands" class="brands">
                                  <option value=""><?php echo $this->__('BRAND') ?></option>
                                    <?php
                                        $cat = Mage::getModel('catalog/category')->load($top_parent_id);
                                        $subcats = $cat->getChildren();

                                            foreach(explode(',',$subcats) as $sub_subCatid)
                                            {echo $sub_subCatid;echo $top_parent_model_id;echo "<br>";
                                                $_sub_category = Mage::getModel('catalog/category')->load($sub_subCatid);
                                                  if($_sub_category->getIsActive()) { ?>
                                            <option value="<?php echo $sub_subCatid;?>" <?php if($sub_subCatid == $top_parent_model_id){echo "selected";}?>><?php echo $_sub_category->getName();?></option>
                                                <?php }
                                             }
                                    ?>
                                </select>

                            </div>

                            <div class="models_wrap">
                                <select name="models" class="models">
                                  <option value=""><?php echo $this->__('MODEL') ?></option>
                                    <?php
                                         $cat = Mage::getModel('catalog/category')->load($top_parent_model_id);
                                         $subcats = $cat->getChildren();

                                             foreach(explode(',',$subcats) as $sub_subCatid)
                                             {
                                                 $_sub_category = Mage::getModel('catalog/category')->load($sub_subCatid);
                                                   if($_sub_category->getIsActive()) { ?>
                                                     <option value="<?php echo $_sub_category->getUrl();?>" <?php if($sub_subCatid == $_categoryId){echo "selected";}?>><?php echo $_sub_category->getName();?></option>
                                                 <?php }
                                              }
                                    ?>
                                </select>

                            </div>

                        </div>

                        <div class="find_design_wrap">
                            <input type="submit" class="find_design" value="FIND DESIGN" name="find_design">
                        </div>

                    </form>

                </div>

            </div>

        </div>

                <div class="current-cat">
                    <img src="<?php echo $this->getSkinUrl('images/mobile-icon.png');?>" />
                    <span><?php echo $_category->getName();?></span>
                </div>

                <!--Breadcrumbs-->
                <div class="breadcrumbs_cover breadcrumbs">
                    <ul>
                        <li class="home">
                            <a href="<?php echo $this->getUrl('');?>" title="Go to Home Page"><?php echo $this->__('Happily Unmarried') ?></a>
                            <img src="<?php echo $this->getSkinUrl('images/general/breadcrumb_separator.png');?>" class="breadcrumb_separator">
                        </li>
                        <li class="home">
                            <a href="<?php echo $this->getUrl('products/phone-covers.html');?>" title="Go to Home Page"><?php echo $this->__('Phone Covers') ?></a>
                            <img src="<?php echo $this->getSkinUrl('images/general/breadcrumb_separator.png');?>" class="breadcrumb_separator">
                        </li>
                        <li class="category85">
                            <a><?php echo $_category->getName();?></a>
                        </li>
                    </ul>
                </div>

                <?php if(!$_productCollection->count()): ?>

                    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>

                <?php else: ?>

                <div class="category-products">

                    <?php // Grid Mode ?>
                    <?php $_collectionSize = $_productCollection->count();?>
                    <?php $_columnCount = $this->getColumnCount(); ?>

                    <ul class="products-grid" id="<?php echo 'container' . $_categoryId; ?>">

                        <?php $i=0; foreach ($_productCollection as $_product): $i++; ?>

                            <li class="item<?php if($i % 3 == 2): echo ' middle'; endif; ?>" id="product_id_<?php echo $_product->getId(); ?>">

                                <a href="<?php echo $_product->getProductUrl() . $searchString ?>">

                                    <div class="product-image" id="<?php echo 'product_' . $_product->getId(); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        <img class="item-image" src="<?php echo $this->getSkinUrl() . 'images/homepage/lazyloader_placeholder.png' ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        <noscript>
                                            <img class="item-image" src="<?php echo $this->getSkinUrl() . 'images/homepage/lazyloader_placeholder.png' ?>" data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                        </noscript>
                                    </div>

                                    <h2 class="product-name">
                                            <?php $name = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                            <?php $thresholdSize = 20; ?>
                                            <?php $nameLength = strlen($name); ?>
                                            <?php $title = 0; ?>
                                            <?php if($nameLength > $thresholdSize) { $title = 1; } ?>
                                        <span class="product_name_title" <?php if($title == 1): ?>title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"<?php endif; ?>>
                                            <?php echo $name ?>
                                        </span>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                    </h2>
                                    <p class="product-short-desc">
                                        <?php echo strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')) ?>
                                    </p>

                                </a>

                            </li>

                        <?php endforeach; ?>

                    </ul>

            </div>

            <?php endif; ?>

    </div>

</div>

<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery("select").msDropdown({roundedBorder:false});
    // jQuery('.brands option:eq(0)').attr('selected','selected');
    // jQuery('.brands_wrap .ddTitleText .ddlabel').text(jQuery('.brands option:eq(0)').text());
    // jQuery('.models option:eq(0)').attr('selected','selected');
    // jQuery('.models_wrap .ddTitleText .ddlabel').text(jQuery('.models option:eq(0)').text());
    jQuery('.brands').live('change', function(e){
        jQuery('#fancybox-loading-overlay').show();
        jQuery('#fancybox-loading').show();
        e.preventDefault();
            jQuery.ajax({
                url: '<?php echo $this->getUrl('explore/cover/subcategories');?>',
                type: 'POST',
                data: 'sub_cat_id=' + jQuery('.brands').val(),
                success: function(return_data) {
                    jQuery('#fancybox-loading-overlay').hide();
                    jQuery('#fancybox-loading').hide();
                    jQuery('.models_wrap').html(return_data);
                    jQuery('.models option:eq(1)').attr('selected','selected');
                    jQuery('.models_wrap .ddTitleText .ddlabel').text(jQuery('.brands option:eq(1)').text());
                    jQuery("select").msDropdown({roundedBorder:false});
                }
            });
    });
    jQuery('.find_design').click(function(e){
        e.preventDefault();
        jQuery('#fancybox-loading-overlay').show();
        jQuery('#fancybox-loading').show();
        window.location = jQuery('.models option:selected').val();

    });
});
</script>
<style>
.one_category {margin:0px; width: 100%;}
.footer-container {margin-top: 71px;}
.footer{margin:0px;}
.current-cat span {color: #707070;
font-size: 35px;
font-family: 'Roboto', arial;
font-weight: 100;
line-height: 32px;}
.current-cat img {float: left;margin-right: 8px;}

.middle_content_cover{
    padding-bottom: 30px;
}

.products-grid li.item{
    margin: 1%  0;
    width: 32%;
    padding:0;
}

.products-grid li.item.middle{
    margin:1% 1.5%;
}

</style>
<?php } ?>
