<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $zoomWidth   = Mage::helper('quickview/quickview')->getZoomWidth();
    $zoomHeight  = Mage::helper('quickview/quickview')->getZoomHeight();
    $zoomPosition  = Mage::helper('quickview/quickview')->getZoomPosition();
	$zoomColor  = Mage::helper('quickview/quickview')->getZoomColor();

	$top  = Mage::helper('quickview/quickview')->getTOP();
	$leftNext  = Mage::helper('quickview/quickview')->getLeftNext();
	$leftPrev  = Mage::helper('quickview/quickview')->getLeftPrev();
	$pHeight  = Mage::helper('quickview/quickview')->getPaginationHeight();
	$pWidth  = Mage::helper('quickview/quickview')->getPaginationWidth();
	$imgWidth  = Mage::helper('quickview/quickview')->getImageWidth();
	$imgHeight  = Mage::helper('quickview/quickview')->getImageHeight();
?>
<script type="text/javascript">
//<![CDATA[
jQuery.noConflict();
jQuery(document).ready(function() {
	// jQuery('.cloud-zoom').CloudZoom({ showTitle: false });
	jQuery(function(){
		jQuery('#product_img_slider').slides({
			preload: false,
			preloadImage: '<?php echo $this->getSkinUrl("md/quickview/images/loadingAnimation.gif"); ?>',
			effect: 'fade',
			crossfade: false,
			slideSpeed: 200,
			fadeSpeed: 200,
			generateNextPrev: true,
			generatePagination: false,
			paginationClass: 'pagination'
		});
	});
});
//]]>
</script>
<style>
#product_img_slider {float: left; width: 390px; }
#product_img_slider .slides_container {float:right; position:relative; border:1px solid #dfdfdf; /* margin-top: 34px; */ }
.slides_container a {display:block; }
#product_img_slider .next,#product_img_slider .prev {overflow: hidden; position: absolute; width: 32px; z-index: 101; }
#product_img_slider .pagination {width:<?php echo ($pWidth+10).'px' ?>; }
#product_img_slider .pagination li a {width:<?php echo $pWidth.'px' ?>; }
</style>

<?php $option = $this->getRequest()->getParam('option'); ?>
<div id="product_img_slider">

	<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>

		<?php if (count($this->getGalleryImages()) > 0): ?>

			<div class="slides_container">
				<?php foreach ($this->getGalleryImages() as $_image): ?>
					<?php $imageLabel = $_image->getLabel(); ?>
					<div id="cloud-zoom" class='cloud-zoom<?php if($option == $imageLabel): echo ' the-active-image-cloud-zoom'; endif; ?>'>
						<img class="prod-img" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(804); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
					</div>
				<?php endforeach; ?>
			</div>

		<?php else:?>

			<p class="product-image">
				<div href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600); ?>" class='cloud-zoom' rel="position:'<?php echo $zoomPosition?>' ,tint: '<?php echo $zoomColor ?>',tintOpacity:0.5 ,smoothMove:5,zoomWidth:<?php echo $zoomWidth?>,zoomHeight:<?php echo $zoomHeight?>,adjustY:-4, adjustX:10, zoomFlyOut:false,zoomSizeMode:'lens' ">
			    <?php
			        $_img = '<img id="image" width="'.$imgWidth.'" height="'.$imgHeight.'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgWidth,$imgHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
			        echo $_helper->productAttribute($_product, $_img, 'image');
			    ?>

				</div>
			</p>

		<?php endif; ?>

	<?php else: ?>

		<p class="product-image">
			<div href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600); ?>" class='cloud-zoom' rel="position:'<?php echo $zoomPosition?>' ,tint: '<?php echo $zoomColor ?>',tintOpacity:0.5 ,smoothMove:5,zoomWidth:<?php echo $zoomWidth?>,zoomHeight:<?php echo $zoomHeight?>,adjustY:-40, adjustX:100, zoomFlyOut:false,zoomSizeMode:'lens' ">

			<?php
				$_img = '<img id="image" width="'.$imgWidth.'" height="'.$imgHeight.'" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($imgWidth,$imgHeight).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
				echo $_helper->productAttribute($_product, $_img, 'image');
			?>

			</div>
		</p>

	<?php endif; ?>
	<!-- <div style="position:absolute; top:0px; left:0px; z-index:100;"> -->
	<div style="overflow: hidden;">
		<div class="image_gallery_content_holder" id="product-image-gallery-icons">
			<div class="image_gallery_content">
				<?php if (count($this->getGalleryImages()) > 0): ?>
					<ul class="pagination">
					<?php foreach ($this->getGalleryImages() as $_image): ?>
						<li>
							<a class="pagination_img" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
								<img class="p_image_hover" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($pWidth,$pHeight); ?>" width="<?php echo $pWidth?>" height="<?php echo $pHeight?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
								<div class="gallery_current_image_mask"></div>
							</a>
						</li>
					<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</div>
		</div>
	</div>


</div>

<div class="zoom-button zoom-in-action"></div>

