

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Filters - jQuery plugin that allows to filter items using custom animation - demo</title>
<script src="<?php echo $this->getSkinUrl('js/filters.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('js/init.js')?>"></script>
<style type="text/css">
	@import url(http://fonts.googleapis.com/css?family=Playball);

/* ------ general
-----------------------------------------------*/

html, body {
padding:0;
margin:0;
height:100%;
min-height:100%;
}

body {
background:url(../images/bg.png) repeat;
font-family:Arial, Helvetica, sans-serif;
font-size:12px;
color:#fff;
}

#content {
margin:0 auto;
width:1000px;
}

.info {
float:left;
width:100%;
margin:20px 0;
padding-bottom:20px;
border-bottom:1px solid #353535;
color:#fff;
position:relative;
}

.info h1 {
font-family:'Playball', serif;
font-size:77px;
font-weight:normal;
margin:0;
margin-bottom:20px;
}

.info p {
float:left;
margin:0;
margin-bottom:6px;
}

.info .demo {
position:absolute;
top:45px;
right:0;
}

.info .demo a {
display:inline-block;
margin-left:10px;
font-weight:bold;
}

.dd {
float:left;
clear:both;
width:960px;
padding:20px;
padding-bottom:10px;
margin:0;
margin-bottom:20px;
background:#ddd;
background:rgba(255, 255, 255, .8);
color:#222;
}

.footer {
float:left;
clear:both;
width:100%;
text-align:center;
font-size:10px;
text-transform:uppercase;
padding:20px 0;
margin-top:20px;
border-top:1px solid #353535;
}

/* ------ filtrey
-----------------------------------------------*/

.filters {
float:left;
clear:both;
width:1000px;
}

.filters .filter {
float:left;
clear:both;
width:960px;
padding:20px;
margin-bottom:20px;
background:#545454;
background:rgba(255, 255, 255, .1);
}

.filters .filter a {
float:left;
display:block;
padding:5px;
margin-right:20px;
font-size:11px;
text-transform:uppercase;
outline:none;
}

.filters .filter .active {
background:#eee;
color:#111;
}

.filters .container {
float:left;
clear:both;
width:100%;
position:relative;
}

.filters .container ul,
.filters .container ul li {
display:block;
list-style:none;
padding:0;
margin:0;
}

.filters .container ul li {
float:left;
margin:0 8px 8px 0;
font-size:0;
line-height:0;
}

.filters .container a {
display:block;
float:left;
width:192px;
height:192px;
}

a {
color:#eee;
text-decoration:none;
}
</style>
</head>

<body>
		
	<div id="content">
		<div class="info">
			<h1>Filters</h1>
			<p>Filters is a jQuery plugin that allows to filter items using custom animation.</p>
			<p>The images in the demo are by <a href="http://www.flickr.com/people/linuz90/" target="_blank">LINUZ90</a> and they are licensed under the Attribution-ShareAlike 2.0 Generic (CC BY-SA 2.0) License.</p>
			<div class="demo">
				Demos:
				<a href="index.html">Basic CSS3</a>
				<a href="demo2.html">Basic fade in/out</a>
				<a href="demo3.html">Fixed position</a>
				<a href="demo4.html">Custom CSS3 transition</a>
			</div>
		</div>
		
		<pre class="dd">
$('.filters').filters();
		</pre>
		
		<div class="filters demo1">
			<div class="filter">
				<a rel="city">City</a>
				<a rel="cars">Cars</a>
				<a rel="other">Other</a>
				<a rel="all">All</a>
			</div>
			<div class="container">
				<ul>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img1.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img6.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img5.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img7.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img3.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img4.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img8.jpg')?>" alt="" /></a>
					</li>
					<li class="cars">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img2.jpg')?>" alt="" /></a>
					</li>
					<li class="other">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img10.jpg')?>" alt="" /></a>
					</li>
					<li class="city">
						<a href="#"><img src="<?php echo $this->getSkinUrl('assets/img12.jpg')?>" alt="" /></a>
					</li>
				</ul>
			</div>
		</div>
		
		<div class="footer">
			All right reserved <a href="http://www.jscraft.net">jscraft.net</a>More script and css style
: <a href="http://www.htmldrive.net/" title="HTML DRIVE - Free DHMTL Scripts,Jquery plugins,Javascript,CSS,CSS3,Html5 Library">www.htmldrive.net </a>
		</div>
	</div>
	
</body>
</html>
