<meta property="og:site_name" content="HappilyUnmarried" />
<meta property="og:title" content="How real is your love? Tell us and win vouchers worth Rs 2500." />
<meta property="og:description" content="This Valentines season, tell us how real is your love. Interesting entries win Vouchers worth Rs 2500. Plus your significant other gets exciting gifts from us on your behalf." />
<meta property="og:type" content="article" />
<meta property="og:image" content="<?php echo Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group9/image');?>" />
<link rel="image_src" href="<?php echo Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group9/image');?>" />
