<div class="congrats_page">
	<h1>Thank You!</h1>

	<p>Results shall be out on 14th Feb 2015.</p>
	<p>Pray that you get lucky!</p>

	<div class="socila_media_div">
		<div class="heading">Spread the Love and Share the Awesomeness!</div>
		<div class="sovial_icon_div">
			<a href="#"><img src="<?php echo $this->getSkinUrl('images/fb-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this->getSkinUrl('images/tw-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this -> getSkinUrl('images/google-icon.png');?>"></a>
			<a href="#"><img src="<?php echo $this -> getSkinUrl('images/pin-icon.png');?>"></a>
		</div>
	</div>
</div>


<div class="main_container_new xmaspage">
	<div class="banner_new">
		<img src="<?php echo $this->getSkinUrl()?>images/banner_new.jpg" />
	</div>

	<div class="news_div">
		<p>Tell us how "real" your love is by filling the form below.The three most real and interesting entries shall win Rs 2500 Happily Unmarried vouchers.And We would also send an exciting gift to your (potential) significant other.</span></p>
	
	</div>

	<div class="form_div">	
		<p>Dearest Happily Unmarried,</p>
		<div class="form_content">
				<!-- <p>(In 50 words maximum, please. We don’t have much of an attention span when drunk! )</p> -->
		<textarea class="form_textarea">
Your Love is as real as...
For example:
Our Love is as real as the hangover after a night of heavy drinking.
(50 words Max! Our attention span is as short as the phonecall between you and your mom! )		</textarea>

		</div>

		<p>Truly in Love,</p>

		<form>
			<div class="input_field"><input type="text"></div>
			<div class="input_field"><input type="text"></div>
			
			<button>SUBMIT</button>
		</form>
	</div>

</div>

