<div class="main_container_new xmaspage valentines">
	<div class="banner_new">
	<img src="<?php echo Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group8/image'); ?>" width="500px;" height="500px;"/>
	</div>

	<div class="breadcrumbs_cover breadcrumbs">
	    <ul>
	        <li class="home">
	            <a href="<?php echo $this->getUrl('');?>" title="<?php echo $this->__("Go to Home Page"); ?>"><?php echo $this->__("Happily Unmarried"); ?></a>
	            <img src="<?php echo $this->getSkinUrl('images/general/breadcrumb_separator.png');?>" class="breadcrumb_separator">
	        </li>
	        <li class="category85">
	            <a href="<?php echo $this->getUrl('');?>keepitreal" ><?php echo $this->__("keepitreal"); ?></a>
	        </li>
	    </ul>
	</div>

	<div class="news_div">
		<p>
			<?php echo $this->__('Tell us how "real" your love is by filling the form below along with your name and email id!.'); ?>
			<br/>
			<?php echo $this->__('The three most real entries will win HU goodies this Valentine.'); ?>
		</p>

		<p><?php echo $this->__("The winners will be announced on 14th of February."); ?> </p>

		<div class="swear_its_true font_weight_500"><?php echo $this->__("#KeepItReal"); ?> </div>
	</div>

	<form id="xxxmas" method="post">

		<div class="form_div">

				<p class="font_weight_500"><?php echo $this->__("Dearest Happily Unmarried,"); ?></p>

				<div class="form_content">

				<textarea class="form_textarea" name="message" id="message" cols="4" rows="7">
"Our Love is as real as the hangover after a night of heavy drinking."

(50 words Max! Our attention span is as short as the phonecall between you and your mom! )</textarea>
				<div class="errorm"><?php echo $this->__("Message can't be left blank!"); ?></div>
			</div>

			<p class="font_weight_500"><?php echo $this->__("Truly in Love,"); ?></p>
				<div class="input_field"><input type="text" id="uname" name="name" placeholder="Your Name" /></div>
				<div class="errorn"><?php echo $this->__("Name can't be left blank!"); ?></div>
				<div class="input_field"><input type="text" id="email" name="email" placeholder="E-mail Address" /></div>
				<div class="errore"><?php echo $this->__("Email can't be left blank!"); ?></div>
				<div class="errorev"><?php echo $this->__("Please enter valid email!"); ?></div>
				<div class="swear_its_true"><?php echo $this->__("You swear it's true?"); ?></div>
				<input type="submit" name="submit" value="Yes I Do" id="submit" class="submit" />
		</div>

	</form>

</div>

<script type="text/javascript">

jQuery(document).ready(function(){

	jQuery("#message").click(function() {
		 if(jQuery("#message").val().indexOf('"Our Love is as real') === -1){
		 }else{
		 	jQuery("#message").val('');
		 }
	});


	jQuery( "#submit" ).click(function(event) {

		 if(jQuery("#message").val().indexOf('"Our Love is as real') === -1){

		 }else{
		 	jQuery('#message').css('border','1px solid red');
			jQuery('.errorm').show();
			return false;
		 }

		event.preventDefault();

		var $name          = jQuery("#uname").val();
		var $email         = jQuery("#email").val();
		var $message       = jQuery("#message").val();

		if($message == ''){
			jQuery('#message').css('border','1px solid red');
			jQuery('.errorm').show();
			return false;
		}else{
			jQuery('#message').css('border','1px solid #b6b6b6');
			jQuery('.errorm').hide();
		}

		if($name == ''){
			jQuery('#uname').css('border','1px solid red');
			jQuery('.errorn').show();
			return false;
		}else{
			jQuery('#uname').css('border','1px solid #b6b6b6');
			jQuery('.errorn').hide();
		}

		if($email == ''){
			jQuery('#email').css('border','1px solid red');
			jQuery('.errore').show();
			return false;
		}else{
			jQuery('#email').css('border','1px solid #b6b6b6');
			jQuery('.errore').hide();
		}

	    if (!ValidateEmail($email)) {
  			jQuery('#email').css('border','1px solid red');
  			jQuery('.errorev').show();
			return false;
		}else{
			jQuery('#email').css('border','1px solid #b6b6b6');
			jQuery('.errorev').hide();
		}

		jQuery('#fancybox-loading-overlay').show();
		jQuery('#fancybox-loading').show();
		jQuery('#popup_jacket').show();
		jQuery('#loading_gif').show();

		jQuery.ajax({
		      url: "<?php echo $this->getUrl('valentines/index/valentines');?>",
		      type: 'post',
		      data: {'name': $name, 'email': $email, 'message': $message},
		      success: function(data) {
			      		jQuery("#uname").val('');
						jQuery("#email").val('');
						jQuery("#message").val('');
						jQuery('.congrats_page').show();
						jQuery('.news_div').hide();
						jQuery('.form_div').hide();
						jQuery(window).scrollTop(320);
			      			jQuery('#fancybox-loading-overlay').hide();
			            		jQuery('#fancybox-loading').hide();
			      			jQuery("#popup_jacket").hide();
						jQuery("#loading_gif").hide();
		      }
	    });

	});

});

function ValidateEmail(email) {
    var expr = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
    return expr.test(email);
}
</script>


<div class="congrats_page">
	<h1><?php echo $this->__("Thank you!"); ?></h1>

	<p><?php echo $this->__("Results shall be out on 14th Feb 2015."); ?></p>
	<p><?php echo $this->__("Pray that you get lucky!"); ?></p>

	<?php
			$title="How real is your love?";
			$url=$this->getUrl('KeepItReal');
			$summary='Tell us and win vouchers worth Rs 2500.';
			$image= Mage::getBaseUrl('media') .'Creativity/'. Mage::getStoreConfig('hubanner/hubanner_group9/image');
	?>

	<div class="socila_media_div">
		<div class="heading"><?php echo $this->__("Spread the Love and Share the Awesomeness!"); ?></div>
		<div class="sovial_icon_div">
			<a href="http://www.facebook.com/sharer.php?s=100&p[url]=<?php echo $url; ?>&p[images][0]=<?php echo $image;?>"><img src="<?php echo $this->getSkinUrl('images/fb-icon.png');?>"></a>

			<a href="https://twitter.com/intent/tweet?text=Tell us how real is your love and win vouchers worth Rs 2500.&hashtags=KeepItReal&via=happilyunmarried&url=<?php echo $url; ?>&via=happilyunmarried"><img src="<?php echo $this->getSkinUrl('images/tw-icon.png');?>"></a>

			<a href="https://plus.google.com/share?url=<?php echo $this->getUrl('');?>keepitreal"><img src="<?php echo $this-> getSkinUrl('images/google-icon.png');?>"></a>
		</div>
	</div>

	<div class="trackyourorder-keepshopping">
		<div class="proceed_to_payment_box">
			<div class="happy_button keep_shopping_button">
				<a href="<?php echo $this->getUrl('');?>" class="happy_button keep_shopping_button">
				<?php echo $this->__("Keep Shopping"); ?>
				</a>
			</div>
		</div>
	</div>
</div>
