<label for="<?php echo $this->getFieldId('gender')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>>
	<?php echo $this->__('Gender') ?>
	<?php if ($this->isRequired()) echo '<sup>*</sup>' ?>
</label>
<div class="data_area">
    <select id="<?php echo $this->getFieldId('gender')?>" name="<?php echo $this->getFieldName('gender')?>" class="billing_gender_select <?php if ($this->isRequired()): echo " validate-select"; endif; ?>" <?php echo $this->getFieldParams() ?>>
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();?>
        <?php $value = $this->getGender();?>
        <?php foreach ($options as $option): if($option['value'] != ''): ?>
            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
        <?php endif; endforeach;?>
    </select>
</div>
