<html>
<title>Confirmation success page</title>
<head></head>
<body style="margin:0;">
<div class="successdiv" style="margin-top:100px !important;width: 600px;height: auto;margin: 0 auto;font-size: 15px;font-family: roboto , arial;color: #181818;line-height: 22px;text-align: center;border: 1px solid #e74c3c;border-radius: 5px;padding: 15px 0px 0 0px;">
	<p class="msg" style="font-weight: bold;font-size: 1.7em;padding-left: 20px;padding-right: 20px;">You have now successfully registered.</p>
	<p style="padding-left: 20px;padding-right: 20px;">Keep your fingers crossed and pray that you guys win.</p>
	<p class="mailer-logo" style="padding-left: 20px;padding-right: 20px;text-align: center;margin: 40px 0 20px;"><img src="<?php echo $this->getSKinUrl('css/images/mailer-logo-2.png');?>"></p>
	<div class="link" style="background: #e74c3c;padding: 8px 10px;"><a href="http://www.happilyunmarried.com/" style="color: #fff;text-decoration: none;">www.happilyunmarried.com</a></div>
</div>
</body>
</html>
