<!--script>!window.jQuery && document.write(unescape('%3Cscript src="<?php // echo $this->getUrl("js/md/quickview/js/jquery-1.7.2.min.js")?>'))</script-->
<!--script src="<?php // echo $this->getSkinUrl('js/jquery-ui.min.js') ?>"></script>
<script src="<?php // echo $this->getSkinUrl('js/jquery.selectBoxIt.js') ?>"></script-->

<script src="<?php echo $this->getSkinUrl('js/product.view.js') ?>"></script>

<script type="text/javascript">
/**
 * 
 * 
 * This script makes the active gallery image draggable
 * 
 * 
 */
// jQuery(document).ready(function($) {

// 	var clicking = false;
// 	var previousX;
// 	var previousY;

// 	$(".slides_container").mousedown(function(e) {
// 		e.preventDefault();
// 		previousX = e.clientX;
// 		previousY = e.clientY;
// 		clicking = true;
// 	});

// 	$(document).mouseup(function() {	      
// 		clicking = false;
// 	});

// 	$(".slides_container").mousemove(function(e) {
// 		if (clicking) {
// 			e.preventDefault();
// 			var directionX = (previousX - e.clientX) > 0 ? 1 : -1;
// 			var directionY = (previousY - e.clientY) > 0 ? 1 : -1;
// 			$(".slides_container").scrollLeft($(".slides_container").scrollLeft() + (previousX - e.clientX));
// 			$(".slides_container").scrollTop($(".slides_container").scrollTop() + (previousY - e.clientY));
// 			previousX = e.clientX;
// 			previousY = e.clientY;
// 		}
// 	});

// 	$(".slides_container").mouseleave(function(e) {
// 		clicking = false;
// 	});

// });
</script>