<?php $_code = $this->getMethodCode(); ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	
	<input type="hidden" id="ccavenue_payment_method" name="payment[ccavenue_payment_method]" />
	<input type="hidden" id="ccavenue_method_option" name="payment[ccavenue_method_option]" />
	
	<li class="ccavenue-payment-option-box">

		<div class="input-box">
			<label for="ccavenue_card_option_1">Pay By ATM-CUM-DEBIT CARD</label>
			<input class="ccavenue-payment-option" name='payment[ccavenue_card_option]' type="radio" id='ccavenue_card_option_1' value='NonMoto' />
		</div>

		<select class="ccavenue-payment-dropdowns" id="ccavenue_non_moto_card_type" name="payment[ccavenue_non_moto_card_type]">
			<option value='' selected="selected"></option>
			<option value ="SBMDBV_Y" >VISA Debit Card Issued in India (VBV)</option>
			<option value ="CANVIS_N" >Canara Bank Debit Card (ATM PIN)</option>
			<option value ="CBIDEB_N" >Citibank Debit Card (IPIN)</option>
			<option value ="IOBDB_N" >Indian Overseas Bank Debit Card (ATM PIN)</option>
			<option value ="PNBM_N" >Punjab National Bank Debit Card (ATM PIN)</option>
			<option value ="UNIDB_N" >Union Bank of India Debit Card (ATM PIN)</option>
			<option value ="SBMDB_Y" >State Bank of India Debit Card</option>
		</select>

	</li>
	
	<li class="ccavenue-payment-option-box">

		<div class="input-box">
			<label for="ccavenue_card_option_2">Pay Using Your Internet Enabled Bank Account</label>
			<input class="ccavenue-payment-option" name='payment[ccavenue_card_option]' value='netBanking' id='ccavenue_card_option_2' type="radio" />
		</div>

		<select class="ccavenue-payment-dropdowns" id="ccavenue_net_banking_cards" size="1" name="payment[ccavenue_net_banking_cards]">
			<option value="" selected="selected"></option>
			<option value ="AND_N" >Andhra Bank</option>
			<option value ="UTI_N" >AXIS Bank</option>
			<option value ="BBK_N" >Bank of Bahrain & Kuwait</option>
			<option value ="BOBCO_N" >Bank of Baroda Corporate Accounts</option>
			<option value ="BOB_N" >Bank of Baroda Retail Accounts</option>
			<option value ="BOI_N" >Bank of India</option>
			<option value ="BOM_N" >Bank of Maharashtra</option>
			<option value ="CAN_N" >Canara Bank</option>
			<option value ="CSB_N" >Catholic Syrian Bank</option>
			<option value ="CEN_N" >Central Bank of India</option>
			<option value ="CBIBAN_N" >Citibank Bank Account Online</option>
			<option value ="CITIUB_N" >City Union Bank</option>
			<option value ="COP_N" >Corporation Bank</option>
			<option value ="DCB_N" >DCB Bank ( Development Credit Bank )</option>
			<option value ="DEUNB_N" >Deutsche Bank</option>
			<option value ="FDEB_N" >Federal Bank</option>
			<option value ="HDEB_N" >HDFC Bank</option>
			<option value ="IDEB_N" >ICICI Bank</option>
			<option value ="IDBI_N" >IDBI Bank</option>
			<option value ="INB_N" >Indian Bank</option>
			<option value ="IOB_N" >Indian Overseas Bank</option>
			<option value ="NIIB_N" >IndusInd Bank</option>
			<option value ="ING_N" >ING Vysya Bank</option>
			<option value ="JKB_N" >Jammu & Kashmir Bank</option>
			<option value ="KTKB_N" >Karnataka Bank</option>
			<option value ="KVB_N" >Karur Vysya Bank</option>
			<option value ="NKMB_N" >Kotak Mahindra Bank</option>
			<option value ="LVB_N" >Lakshmi Vilas Bank NetBanking</option>
			<option value ="OBC_N" >Oriental Bank of Commerce</option>
			<option value ="PNBCO_N" >Punjab National Bank Corporate Accounts</option>
			<option value ="NPNB_N" >Punjab National Bank Retail Accounts</option>
			<option value ="SIB_N" >South Indian Bank</option>
			<option value ="SCB_N" >Standard Chartered Bank</option>
			<option value ="SBJ_N" >State Bank of Bikaner and Jaipur</option>
			<option value ="SBH_N" >State Bank of Hyderabad</option>
			<option value ="SBI_N" >State Bank of India</option>
			<option value ="SBM_N" >State Bank of Mysore</option>
			<option value ="SBP_N" >State Bank of Patiala</option>
			<option value ="SBT_N" >State Bank of Travancore</option>
			<option value ="SYNBK_N" >Syndicate Bank</option>
			<option value ="TNMB_N" >Tamilnad Mercantile Bank</option>
			<option value ="UNI_N" >Union Bank of India</option>
			<option value ="UBI_N" >United Bank of India</option>
			<option value ="VJYA_N" >Vijaya Bank</option>
			<option value ="YES_N" >YES Bank</option>
		</select>

	</li>
	
	<li class="ccavenue-payment-option-box">

		<div class="input-box">
			<label for="ccavenue_card_option_3">Pay by ITZ CASH CARDS</label>
			<input class="ccavenue-payment-option" name='payment[ccavenue_card_option]' value='CCRD' id='ccavenue_card_option_3' type="radio" />
		</div>

		<select class="ccavenue-payment-dropdowns" id="ccavenue_ccrdtype" size="1" name="payment[ccavenue_ccrdtype]">
			<option value=''></option>
			<option value ="CCI_N" >ICash Card</option>
			<option value ="ITZ_N" >Itz Cash / noQ 24x7</option>
			<option value ="OXIG_N" >OxiCash Card</option>
			<option value ="PCC_N" >PayCash Card</option>
		</select>

	</li>

</ul>

<div>
	<?php echo $this->getMethod()->getConfigData('message'); ?>
</div>

<script type="text/javascript">
jQuery(document).ready(function($) {

	$('.ccavenue-payment-dropdowns').hide();

	$('.ccavenue-payment-option').live('click', function(event) {

		if(event.handled !== true) {

			event.preventDefault();

			var li = $(this).parent().parent();
			$('.ccavenue-payment-dropdowns').hide();
			$('.ccavenue-payment-dropdowns', li).show();

			var ccavenue_payment_method = $(this).val();
			var ccavenue_method_option = $('.ccavenue-payment-dropdowns', li).val();
			
			$('#ccavenue_payment_method').val(ccavenue_payment_method);
			$('#ccavenue_method_option').val(ccavenue_method_option);

			event.handled = true;

		}
		return false;

	});

	$('.ccavenue-payment-dropdowns').live('change', function(event) {

		if(event.handled !== true) {

			event.preventDefault();
			
			var id = $(this).attr('id');
			var ccavenue_method_option = $('#' + id).val();
			$('#ccavenue_method_option').val(ccavenue_method_option);

			event.handled = true;

		}
		return false;

	});

});
</script>
