<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="onepagecheckout_forgotbox" class='op_login_area' style="display:none;">
	<!--div class='close_la' onclick='close_login();'></div>
    <div class="page-title">
        <span><?php // echo $this->__('Forgot Password?') ?></span>
    </div-->
<?php
$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$forgot_url	= str_replace('http:', 'https:', $forgot_url);
?>
    <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form" autocomplete="on">
        <div class="boxcontent">
            <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
			<div class='full'>
				<div class="data_area">
					<input type="email" name="email" alt="email" id="email_address" class="t1 input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" placeholder="Email *" />
				</div>
            </div>
        </div>
        <div class="buttons-set">
            <button type="submit" id="btn-forgot" class="button happy_button"><?php echo $this->__('Submit') ?></button>

            <p class="back-link">
                <a href="javascript:void(0)" class="onepagecheckout_loginlink" onclick='open_login();'>
                    <?php echo $this->__('Back') ?>
                </a>
            </p>

            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('forgot-password-form', true);
    //]]>
    </script>
</div>
<?php }?>
